/* ClipHub Stage 5 number pagination ES5 loader. */
(function(g){
var F=Packages.java.io.File,I=Packages.java.io.FileInputStream,O=Packages.java.io.FileOutputStream,B=Packages.java.io.ByteArrayOutputStream,G=Packages.java.util.zip.GZIPInputStream,A=Packages.android.util.Base64,R=Packages.java.lang.reflect.Array,Y=Packages.java.lang.Byte,S=Packages.java.lang.String,U=Packages.java.net.URL,E=Packages.java.net.URLEncoder,D=Packages.java.security.MessageDigest,T=Packages.java.lang.System;
var C="f1fc8f44e64205dabdb18c9fd0f0465e0180c29d",P="src/ch_11_filter.js",H="adb4f246bfb5fcafd14a36f2a5d8bd412d0a19fe",N="ch_11_filter_stage2_base.js",V="agent/add-pagination-lazy-prefetch-20260807",K=["stage-assets/pagination-stage5/ch11_patch_00.b64","stage-assets/pagination-stage5/ch11_patch_01.b64","stage-assets/pagination-stage5/ch11_patch_02.b64","stage-assets/pagination-stage5/ch11_patch_03.b64","stage-assets/pagination-stage5/ch11_patch_04.b64"],J="2d8a1c981fb5054972e5ba72daf225bba7a4d889c2f525f49659cc68e9652b19",W="ch_11_filter_stage5_patch.b64";
function c(x){if(x!==null&&x!==undefined){try{x.close();}catch(z){}}}
function b(x){var o=new B(),a=R.newInstance(Y.TYPE,8192),n;try{while((n=x.read(a))>=0){if(n>0)o.write(a,0,n);}return o.toByteArray();}finally{c(x);c(o);}}
function r(f){return String(new S(b(new I(f)),"UTF-8"));}
function d(f){if(!f.exists()&&!f.mkdirs()&&!f.isDirectory())throw new Error("mkdir "+f);return f;}
function w(f,s){var t=new F(d(f.getParentFile()),f.getName()+".tmp"),o=null;try{o=new O(t,false);o.write(new S(String(s)).getBytes("UTF-8"));o.flush();}finally{c(o);}if(f.exists()&&!f.delete()){t.delete();throw new Error("replace "+f);}if(!t.renameTo(f)){t.delete();throw new Error("commit "+f);}}
function x(s,n){var q=new S(String(s)).getBytes("UTF-8"),m=D.getInstance(n),a=m.digest(q),o=[],i,v;for(i=0;i<a.length;i+=1){v=Number(a[i]);if(v<0)v+=256;o.push((v<16?"0":"")+v.toString(16));}return o.join("");}
function h(s){var q=new S(String(s)).getBytes("UTF-8"),p=new S("blob "+String(q.length)+"\u0000").getBytes("UTF-8"),m=D.getInstance("SHA-1"),a,o=[],i,v;m.update(p);m.update(q);a=m.digest();for(i=0;i<a.length;i+=1){v=Number(a[i]);if(v<0)v+=256;o.push((v<16?"0":"")+v.toString(16));}return o.join("");}
function n(){var o=g.ClipHubBootstrapOptions||{},q=o.runtimeName===undefined?"ClipHub":String(o.runtimeName);if(!/^[A-Za-z0-9._-]+$/.test(q)||q==="."||q==="..")throw new Error("runtime "+q);return q;}
function u(v,p,t){var q=null,k,z;try{q=new U("https://raw.githubusercontent.com/7015725/ClipHub/"+String(E.encode(v,"UTF-8")).replace(/\+/g,"%20")+"/"+String(E.encode(p,"UTF-8")).replace(/%2F/g,"/").replace(/\+/g,"%20")+"?"+t+"="+Number(T.currentTimeMillis())).openConnection();q.setConnectTimeout(10000);q.setReadTimeout(30000);q.setUseCaches(false);q.setRequestProperty("Accept-Encoding","identity");k=Number(q.getResponseCode());z=String(new S(b(k>=200&&k<300?q.getInputStream():q.getErrorStream()),"UTF-8"));if(k<200||k>=300)throw new Error("HTTP "+k+" "+p);return z;}finally{if(q!==null)try{q.disconnect();}catch(e){}}}
function v(f){var q;if(!f.isFile())return null;try{q=r(f);return h(q)===H?q:null;}catch(e){return null;}}
function l(){if(typeof shortx==="undefined"||typeof shortx.getShortXDir!=="function")throw new Error("ShortX unavailable");var q=new F(String(shortx.getShortXDir()),n()),a=new F(new F(q,"modules.backup"),"ch_11_filter.js"),e=new F(d(new F(q,"cache")),N),z=v(a);if(z!==null){try{w(e,z);}catch(i){}return z;}z=v(e);if(z!==null)return z;z=u(C,P,"s5base");if(h(z)!==H)throw new Error("base sha");w(e,z);return z;}
function j(){var q=new F(String(shortx.getShortXDir()),n()),e=new F(d(new F(q,"cache")),W),z="",i;if(e.isFile()){try{z=r(e);if(x(z,"SHA-256")===J)return z;}catch(a){}}z="";for(i=0;i<K.length;i+=1)z+=u(V,K[i],"s5patch");if(x(z,"SHA-256")!==J)throw new Error("patch sha");w(e,z);return z;}
function z(){var q=new G(new Packages.java.io.ByteArrayInputStream(A.decode(j(),A.DEFAULT)));return String(new S(b(q),"UTF-8"));}
function p(s){var a=JSON.parse(z()),i,k;for(i=0;i<a.length;i+=1){k=s.indexOf(a[i].find);if(k<0||s.indexOf(a[i].find,k+a[i].find.length)>=0)throw new Error("anchor "+a[i].label);s=s.substring(0,k)+a[i].replace+s.substring(k+a[i].find.length);}return s;}
try{eval(p(l()));}catch(e){throw new Error("ch_11_filter.js Stage 5 loader failed: "+String(e));}
}((function(){return this;}())));
