/* ClipHub Stage 16C compatibility-key recycle selection ES5 loader. */
(function (global) {
    var File = Packages.java.io.File;
    var FIS = Packages.java.io.FileInputStream;
    var FOS = Packages.java.io.FileOutputStream;
    var BAOS = Packages.java.io.ByteArrayOutputStream;
    var ReflectArray = Packages.java.lang.reflect.Array;
    var JavaByte = Packages.java.lang.Byte;
    var JavaString = Packages.java.lang.String;
    var URL = Packages.java.net.URL;
    var MessageDigest = Packages.java.security.MessageDigest;
    var Base64 = Packages.android.util.Base64;

    var BASE_URL =
        "https://raw.githubusercontent.com/7015725/ClipHub/" +
        "338a811e538ab526b59eed05102d4f4b66f19953/" +
        "src/ch_11_filter.js";
    var BASE_BLOB_SHA1 = "160cbf0aa482868042c89dad33eae990ccd93488";
    var CACHE_NAME = "ch_11_filter_stage16b_baseline_loader.js";
    var PATCH_B64 =
        "ICAgIGZ1bmN0aW9uIHRyYW5zZm9ybVJlY3ljbGVGaXhTb3VyY2Uoc291cmNlKSB7CiAgICAgICAgdmFyIGluZm87CiAgICAgICAgdmFyIHZhbHVlOwoKICAg" +
        "ICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgICAgICAgICAgICJNT0RVTEVfVkVSU0lPTjogNTkiLCAiTU9EVUxFX1ZFUlNJT046" +
        "IDYwIiwKICAgICAgICAgICAgIlN0YWdlMTZCMSBtb2R1bGUgdmVyc2lvbiIpOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2Us" +
        "CiAgICAgICAgICAgICIgICAgICAgIGhvbGRlck5ld0J1aWxkQ291bnQ6IDBcbiIsCiAgICAgICAgICAgICIgICAgICAgIGhvbGRlck5ld0J1aWxkQ291bnQ6" +
        "IDAsXG4iICsKICAgICAgICAgICAgIiAgICAgICAgaG9sZGVyUmViaW5kQXR0ZW1wdENvdW50OiAwLFxuIiArCiAgICAgICAgICAgICIgICAgICAgIGhvbGRl" +
        "clJlYmluZEVsaWdpYmxlQ291bnQ6IDAsXG4iICsKICAgICAgICAgICAgIiAgICAgICAgaG9sZGVyUmViaW5kSW5lbGlnaWJsZUNvdW50OiAwLFxuIiArCiAg" +
        "ICAgICAgICAgICIgICAgICAgIGhvbGRlclJlYmluZEZhaWx1cmVDb3VudDogMCxcbiIgKwogICAgICAgICAgICAiICAgICAgICBob2xkZXJSZWJpbmRMYXN0" +
        "UmVqZWN0UmVhc29uOiBcIlwiLFxuIiArCiAgICAgICAgICAgICIgICAgICAgIGhvbGRlclJlYmluZExhc3RGYWlsdXJlU3RhZ2U6IFwiXCIsXG4iICsKICAg" +
        "ICAgICAgICAgIiAgICAgICAgaG9sZGVyUmViaW5kTGFzdEVycm9yOiBcIlwiLFxuIiArCiAgICAgICAgICAgICIgICAgICAgIGhvbGRlclJlYmluZFJlamVj" +
        "dFJlYXNvbnM6IHt9LFxuIiArCiAgICAgICAgICAgICIgICAgICAgIGhvbGRlclJlYmluZEZhaWx1cmVTdGFnZXM6IHt9XG4iLAogICAgICAgICAgICAiU3Rh" +
        "Z2UxNkIxIG1ldHJpY3MiKTsKCiAgICAgICAgc291cmNlID0gcmVwbGFjZU9uY2VTdHJpY3Qoc291cmNlLAogICAgICAgICAgICAiICAgICAgICBzY3JvbGxQ" +
        "ZXJmb3JtYW5jZVN0YXRlLmhvbGRlck5ld0J1aWxkQ291bnQgPSAwO1xuIiwKICAgICAgICAgICAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5o" +
        "b2xkZXJOZXdCdWlsZENvdW50ID0gMDtcbiIgKwogICAgICAgICAgICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZEF0dGVt" +
        "cHRDb3VudCA9IDA7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRFbGlnaWJsZUNvdW50ID0g" +
        "MDtcbiIgKwogICAgICAgICAgICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZEluZWxpZ2libGVDb3VudCA9IDA7XG4iICsK" +
        "ICAgICAgICAgICAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRGYWlsdXJlQ291bnQgPSAwO1xuIiArCiAgICAgICAgICAg" +
        "ICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmViaW5kTGFzdFJlamVjdFJlYXNvbiA9IFwiXCI7XG4iICsKICAgICAgICAgICAgIiAg" +
        "ICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRMYXN0RmFpbHVyZVN0YWdlID0gXCJcIjtcbiIgKwogICAgICAgICAgICAiICAgICAg" +
        "ICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZExhc3RFcnJvciA9IFwiXCI7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgc2Nyb2xsUGVy" +
        "Zm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRSZWplY3RSZWFzb25zID0ge307XG4iICsKICAgICAgICAgICAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VT" +
        "dGF0ZS5ob2xkZXJSZWJpbmRGYWlsdXJlU3RhZ2VzID0ge307XG4iLAogICAgICAgICAgICAiU3RhZ2UxNkIxIG1ldHJpYyByZXNldCIpOwoKICAgICAgICBz" +
        "b3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgICAgICAgICAgICIgICAgICAgICAgICBob2xkZXJOZXdCdWlsZENvdW50OlxuIiArCiAgICAg" +
        "ICAgICAgICIgICAgICAgICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyTmV3QnVpbGRDb3VudCksXG4iICsKICAgICAgICAg" +
        "ICAgIiAgICAgICAgICAgIHBlbmRpbmdPcmlnaW46IHZpcnR1YWxQZW5kaW5nT3JpZ2luLFxuIiwKICAgICAgICAgICAgIiAgICAgICAgICAgIGhvbGRlck5l" +
        "d0J1aWxkQ291bnQ6XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJOZXdCdWls" +
        "ZENvdW50KSxcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyUmViaW5kQXR0ZW1wdENvdW50OlxuIiArCiAgICAgICAgICAgICIgICAgICAg" +
        "ICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmViaW5kQXR0ZW1wdENvdW50KSxcbiIgKwogICAgICAgICAgICAiICAgICAg" +
        "ICAgICAgaG9sZGVyUmViaW5kRWxpZ2libGVDb3VudDpcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5j" +
        "ZVN0YXRlLmhvbGRlclJlYmluZEVsaWdpYmxlQ291bnQpLFxuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBob2xkZXJSZWJpbmRJbmVsaWdpYmxlQ291" +
        "bnQ6XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRJbmVsaWdpYmxl" +
        "Q291bnQpLFxuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBob2xkZXJSZWJpbmRGYWlsdXJlQ291bnQ6XG4iICsKICAgICAgICAgICAgIiAgICAgICAg" +
        "ICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRGYWlsdXJlQ291bnQpLFxuIiArCiAgICAgICAgICAgICIgICAgICAg" +
        "ICAgICBob2xkZXJSZWJpbmRMYXN0UmVqZWN0UmVhc29uOlxuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICAgICAgU3RyaW5nKHNjcm9sbFBlcmZvcm1h" +
        "bmNlU3RhdGUuaG9sZGVyUmViaW5kTGFzdFJlamVjdFJlYXNvbiB8fCBcIlwiKSxcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyUmViaW5k" +
        "TGFzdEZhaWx1cmVTdGFnZTpcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAgIFN0cmluZyhzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJl" +
        "YmluZExhc3RGYWlsdXJlU3RhZ2UgfHwgXCJcIiksXG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIGhvbGRlclJlYmluZExhc3RFcnJvcjpcbiIgKwog" +
        "ICAgICAgICAgICAiICAgICAgICAgICAgICAgIFN0cmluZyhzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZExhc3RFcnJvciB8fCBcIlwiKSxc" +
        "biIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyUmViaW5kUmVqZWN0UmVhc29uczpcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAg" +
        "IHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmViaW5kUmVqZWN0UmVhc29ucyxcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyUmVi" +
        "aW5kRmFpbHVyZVN0YWdlczpcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmViaW5kRmFp" +
        "bHVyZVN0YWdlcyxcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgcGVuZGluZ09yaWdpbjogdmlydHVhbFBlbmRpbmdPcmlnaW4sXG4iLAogICAgICAg" +
        "ICAgICAiU3RhZ2UxNkIxIG1ldHJpYyBjb3B5Iik7CgogICAgICAgIGluZm8gPSBzZWN0aW9uKHNvdXJjZSwKICAgICAgICAgICAgIiAgICBmdW5jdGlvbiBy" +
        "ZWJpbmRSZXN1bHRDYXJkSG9sZGVyKGhvbGRlciwgcm93LCBjb2xvcnMpIHsiLAogICAgICAgICAgICAiXG4gICAgZnVuY3Rpb24gbWFrZVJlc3VsdENhcmQo" +
        "IiwKICAgICAgICAgICAgIlN0YWdlMTZCMSByZWJpbmQgZnVuY3Rpb24iKTsKICAgICAgICB2YWx1ZSA9CiAgICAgICAgICAgICIgICAgZnVuY3Rpb24gbm90" +
        "ZUNhcmRIb2xkZXJSZWJpbmRSZWFzb24obWFwLCByZWFzb24pIHtcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIga2V5ID0gU3RyaW5nKHJlYXNvbiB8" +
        "fCBcInVua25vd25cIik7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgaWYgKG1hcFtrZXldID09PSB1bmRlZmluZWQgfHwgbWFwW2tleV0gPT09IG51bGwp" +
        "IHsgbWFwW2tleV0gPSAwOyB9XG4iICsKICAgICAgICAgICAgIiAgICAgICAgbWFwW2tleV0gPSBOdW1iZXIobWFwW2tleV0pICsgMTtcbiIgKwogICAgICAg" +
        "ICAgICAiICAgICAgICByZXR1cm4ga2V5O1xuIiArCiAgICAgICAgICAgICIgICAgfVxuXG4iICsKICAgICAgICAgICAgIiAgICBmdW5jdGlvbiByZWJpbmRS" +
        "ZXN1bHRDYXJkSG9sZGVyKGhvbGRlciwgcm93LCBjb2xvcnMpIHtcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgc3RhcnRlZEF0ID0gTnVtYmVyKFN5" +
        "c3RlbS5jdXJyZW50VGltZU1pbGxpcygpKTtcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgZWxhcHNlZDtcbiIgKwogICAgICAgICAgICAiICAgICAg" +
        "ICB2YXIgc3RhZ2UgPSBcInZhbGlkYXRlXCI7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgdmFyIG9sZFJvdztcbiIgKwogICAgICAgICAgICAiICAgICAg" +
        "ICB2YXIgb2xkVGFncztcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgbmV3VGFncztcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgb2xkU2Vs" +
        "ZWN0ZWQ7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgdmFyIG5ld1NlbGVjdGVkO1xuIiArCiAgICAgICAgICAgICIgICAgICAgIHZhciBvbGRQaW5uZWQ7" +
        "XG4iICsKICAgICAgICAgICAgIiAgICAgICAgdmFyIG5ld1Bpbm5lZDtcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgb2xkUGFja2FnZTtcbiIgKwog" +
        "ICAgICAgICAgICAiICAgICAgICB2YXIgbmV3UGFja2FnZTtcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgb2xkSGFzVGFncztcbiIgKwogICAgICAg" +
        "ICAgICAiICAgICAgICB2YXIgbmV3SGFzVGFncztcbiIgKwogICAgICAgICAgICAiICAgICAgICB2YXIgcmVhc29uID0gXCJcIjtcbiIgKwogICAgICAgICAg" +
        "ICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZEF0dGVtcHRDb3VudCArPSAxO1xuIiArCiAgICAgICAgICAgICIgICAgICAg" +
        "IGlmIChob2xkZXIgPT09IG51bGwgfHwgaG9sZGVyID09PSB1bmRlZmluZWQgfHwgcm93ID09PSBudWxsIHx8IHJvdyA9PT0gdW5kZWZpbmVkIHx8XG4iICsK" +
        "ICAgICAgICAgICAgIiAgICAgICAgICAgICAgICBob2xkZXIucm93ID09PSBudWxsIHx8IGhvbGRlci5yb3cgPT09IHVuZGVmaW5lZCB8fFxuIiArCiAgICAg" +
        "ICAgICAgICIgICAgICAgICAgICAgICAgaG9sZGVyLmNvbnRlbnRWaWV3ID09PSBudWxsIHx8IGhvbGRlci5jb250ZW50VmlldyA9PT0gdW5kZWZpbmVkIHx8" +
        "XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgICAgICBob2xkZXIudGFnQmFkZ2UgPT09IG51bGwgfHwgaG9sZGVyLnRhZ0JhZGdlID09PSB1bmRlZmlu" +
        "ZWQgfHxcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAgIGhvbGRlci5zb3VyY2VWaWV3ID09PSBudWxsIHx8IGhvbGRlci5zb3VyY2VWaWV3ID09" +
        "PSB1bmRlZmluZWQpIHtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgcmVhc29uID0gbm90ZUNhcmRIb2xkZXJSZWJpbmRSZWFzb24oc2Nyb2xsUGVy" +
        "Zm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRSZWplY3RSZWFzb25zLCBcImludmFsaWRfaG9sZGVyXCIpO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAg" +
        "ICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZEluZWxpZ2libGVDb3VudCArPSAxO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBz" +
        "Y3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZExhc3RSZWplY3RSZWFzb24gPSByZWFzb247XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAg" +
        "IHJldHVybiBmYWxzZTtcbiIgKwogICAgICAgICAgICAiICAgICAgICB9XG4iICsKICAgICAgICAgICAgIiAgICAgICAgdHJ5IHtcbiIgKwogICAgICAgICAg" +
        "ICAiICAgICAgICAgICAgb2xkUm93ID0gaG9sZGVyLnJvdztcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgc3RhZ2UgPSBcImVsaWdpYmlsaXR5XCI7" +
        "XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIG9sZFNlbGVjdGVkID0gaG9sZGVyLnNlbGVjdGVkID09PSB0cnVlO1xuIiArCiAgICAgICAgICAgICIg" +
        "ICAgICAgICAgICBuZXdTZWxlY3RlZCA9IFNFTEVDVElPTl9FTkFCTEVEICYmIHNlbGVjdGVkSXRlbUlkICE9PSBudWxsICYmIE51bWJlcihzZWxlY3RlZEl0" +
        "ZW1JZCkgPT09IE51bWJlcihyb3cuaWQpO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBvbGRQaW5uZWQgPSBob2xkZXIucGlubmVkID09PSB0cnVl" +
        "O1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBuZXdQaW5uZWQgPSBOdW1iZXIocm93LmlzX3Bpbm5lZCB8fCAwKSA9PT0gMTtcbiIgKwogICAgICAg" +
        "ICAgICAiICAgICAgICAgICAgb2xkUGFja2FnZSA9IFN0cmluZyhob2xkZXIuc291cmNlUGFja2FnZSB8fCBvbGRSb3cuc291cmNlX3BhY2thZ2UgfHwgXCJc" +
        "Iik7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIG5ld1BhY2thZ2UgPSBTdHJpbmcocm93LnNvdXJjZV9wYWNrYWdlIHx8IFwiXCIpO1xuIiArCiAg" +
        "ICAgICAgICAgICIgICAgICAgICAgICBvbGRUYWdzID0gdGFnc0ZvclJlc3VsdChvbGRSb3cpO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBuZXdU" +
        "YWdzID0gdGFnc0ZvclJlc3VsdChyb3cpO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBvbGRIYXNUYWdzID0gb2xkVGFncy5sZW5ndGggPiAwO1xu" +
        "IiArCiAgICAgICAgICAgICIgICAgICAgICAgICBuZXdIYXNUYWdzID0gbmV3VGFncy5sZW5ndGggPiAwO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAg" +
        "ICBpZiAob2xkU2VsZWN0ZWQgIT09IG5ld1NlbGVjdGVkKSB7IHJlYXNvbiA9IFwic2VsZWN0ZWRfY2hhbmdlZFwiOyB9XG4iICsKICAgICAgICAgICAgIiAg" +
        "ICAgICAgICAgIGVsc2UgaWYgKG9sZFBpbm5lZCAhPT0gbmV3UGlubmVkKSB7IHJlYXNvbiA9IFwicGlubmVkX2NoYW5nZWRcIjsgfVxuIiArCiAgICAgICAg" +
        "ICAgICIgICAgICAgICAgICBlbHNlIGlmIChvbGRQYWNrYWdlICE9PSBuZXdQYWNrYWdlKSB7IHJlYXNvbiA9IFwic291cmNlX3BhY2thZ2VfY2hhbmdlZFwi" +
        "OyB9XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIGVsc2UgaWYgKG9sZEhhc1RhZ3MgIT09IG5ld0hhc1RhZ3MpIHsgcmVhc29uID0gXCJ0YWdfcHJl" +
        "c2VuY2VfY2hhbmdlZFwiOyB9XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIGlmIChyZWFzb24ubGVuZ3RoID4gMCkge1xuIiArCiAgICAgICAgICAg" +
        "ICIgICAgICAgICAgICAgICAgcmVhc29uID0gbm90ZUNhcmRIb2xkZXJSZWJpbmRSZWFzb24oc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRS" +
        "ZWplY3RSZWFzb25zLCByZWFzb24pO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJp" +
        "bmRJbmVsaWdpYmxlQ291bnQgKz0gMTtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVi" +
        "aW5kTGFzdFJlamVjdFJlYXNvbiA9IHJlYXNvbjtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgICAgIHJldHVybiBmYWxzZTtcbiIgKwogICAgICAg" +
        "ICAgICAiICAgICAgICAgICAgfVxuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZEVsaWdp" +
        "YmxlQ291bnQgKz0gMTtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgc3RhZ2UgPSBcImNvbnRlbnRfdGV4dFwiO1xuIiArCiAgICAgICAgICAgICIg" +
        "ICAgICAgICAgICBob2xkZXIuY29udGVudFZpZXcuc2V0VGV4dChTdHJpbmcocmVzdWx0UHJldmlld1RleHQocm93KSkpO1xuIiArCiAgICAgICAgICAgICIg" +
        "ICAgICAgICAgICBzdGFnZSA9IFwidGFnX3RleHRcIjtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyLnRhZ0JhZGdlLnNldFRleHQoU3Ry" +
        "aW5nKChuZXdUYWdzLmxlbmd0aCA+IDAgPyBcIuKXjyAgXCIgOiBcIlwiKSArIHRhZ1N1bW1hcnkobmV3VGFncykpKTtcbiIgKwogICAgICAgICAgICAiICAg" +
        "ICAgICAgICAgc3RhZ2UgPSBcInRhZ19jb2xvclwiO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBob2xkZXIudGFnQmFkZ2Uuc2V0VGV4dENvbG9y" +
        "KG5ld1RhZ3MubGVuZ3RoID4gMCA/IHRhZ0NvbG9yVGV4dChuZXdUYWdzWzBdLCBjb2xvcnMuYWNjZW50U3Ryb25nKSA6IGNvbG9ycy50ZXh0VGVydGlhcnkp" +
        "O1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICBzdGFnZSA9IFwic291cmNlX3RleHRcIjtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9s" +
        "ZGVyLnNvdXJjZVZpZXcuc2V0VGV4dChTdHJpbmcoc291cmNlTGFiZWwocm93KSArIFwiIMK3IFwiICsgZm9ybWF0VGltZShyb3cubGFzdF9jb3BpZWRfYXQp" +
        "KSk7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIHN0YWdlID0gXCJjb21taXRcIjtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVy" +
        "LnJvdyA9IHJvdztcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyLml0ZW1JZCA9IE51bWJlcihyb3cuaWQpO1xuIiArCiAgICAgICAgICAg" +
        "ICIgICAgICAgICAgICBob2xkZXIuc2VsZWN0ZWQgPSBuZXdTZWxlY3RlZDtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyLnBpbm5lZCA9" +
        "IG5ld1Bpbm5lZDtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgaG9sZGVyLnNvdXJjZVBhY2thZ2UgPSBuZXdQYWNrYWdlO1xuIiArCiAgICAgICAg" +
        "ICAgICIgICAgICAgICAgICBlbGFwc2VkID0gTWF0aC5tYXgoMCwgTnVtYmVyKFN5c3RlbS5jdXJyZW50VGltZU1pbGxpcygpKSAtIHN0YXJ0ZWRBdCk7XG4i" +
        "ICsKICAgICAgICAgICAgIiAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmViaW5kQ291bnQgKz0gMTtcbiIgKwogICAgICAgICAg" +
        "ICAiICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRMYXN0TXMgPSBlbGFwc2VkO1xuIiArCiAgICAgICAgICAgICIgICAg" +
        "ICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlYmluZE1heE1zID0gTWF0aC5tYXgoTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUu" +
        "aG9sZGVyUmViaW5kTWF4TXMpLCBlbGFwc2VkKTtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgcmV0dXJuIHRydWU7XG4iICsKICAgICAgICAgICAg" +
        "IiAgICAgICAgfSBjYXRjaCAoZXJyb3IpIHtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJp" +
        "bmRGYWlsdXJlQ291bnQgKz0gMTtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRMYXN0" +
        "RmFpbHVyZVN0YWdlID0gbm90ZUNhcmRIb2xkZXJSZWJpbmRSZWFzb24oc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWJpbmRGYWlsdXJlU3RhZ2Vz" +
        "LCBzdGFnZSk7XG4iICsKICAgICAgICAgICAgIiAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmViaW5kTGFzdEVycm9yID0gU3Ry" +
        "aW5nKGVycm9yKTtcbiIgKwogICAgICAgICAgICAiICAgICAgICAgICAgdmlydHVhbFN0YXRlLmxhc3RFcnJvciA9IFwiQ2FyZEhvbGRlciByZWJpbmQgZmFp" +
        "bGVkIGF0IFwiICsgc3RhZ2UgKyBcIjogXCIgKyBTdHJpbmcoZXJyb3IpO1xuIiArCiAgICAgICAgICAgICIgICAgICAgICAgICByZXR1cm4gZmFsc2U7XG4i" +
        "ICsKICAgICAgICAgICAgIiAgICAgICAgfVxuIiArCiAgICAgICAgICAgICIgICAgfVxuIjsKICAgICAgICBzb3VyY2UgPSByZXBsYWNlU2VjdGlvbihzb3Vy" +
        "Y2UsIGluZm8sIHZhbHVlKTsKCiAgICAgICAgaWYgKHNvdXJjZS5pbmRleE9mKCJNT0RVTEVfVkVSU0lPTjogNjAiKSA8IDAgfHwKICAgICAgICAgICAgICAg" +
        "IHNvdXJjZS5pbmRleE9mKCJob2xkZXJSZWJpbmRBdHRlbXB0Q291bnQiKSA8IDAgfHwKICAgICAgICAgICAgICAgIHNvdXJjZS5pbmRleE9mKCJob2xkZXJS" +
        "ZWJpbmRGYWlsdXJlU3RhZ2VzIikgPCAwIHx8CiAgICAgICAgICAgICAgICBzb3VyY2UuaW5kZXhPZigiaG9sZGVyLmNvbnRlbnRWaWV3LnNldFRleHQoU3Ry" +
        "aW5nKHJlc3VsdFByZXZpZXdUZXh0KHJvdykpKSIpIDwgMCkgewogICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoIlN0YWdlMTZCMSBzYWZlIHJlYmluZCB3" +
        "aXJpbmcgaW5jb21wbGV0ZSIpOwogICAgICAgIH0KICAgICAgICByZXR1cm4gc291cmNlOwogICAgfQoKZnVuY3Rpb24gdHJhbnNmb3JtU3RhZ2UxNkIyU291" +
        "cmNlKHNvdXJjZSkgewogICAgICAgIHZhciBvbGRBbGlnbm1lbnQ7CiAgICAgICAgdmFyIG5ld0FsaWdubWVudDsKICAgICAgICBzb3VyY2UgPSByZXBsYWNl" +
        "T25jZVN0cmljdChzb3VyY2UsCiAgIk1PRFVMRV9WRVJTSU9OOiA2MCIsICJNT0RVTEVfVkVSU0lPTjogNjEiLAogICJTdGFnZTE2QjIgbW9kdWxlIHZlcnNp" +
        "b24iKTsKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgIiAgICAgICAgYWxpZ25tZW50RmFsbGJhY2tDb3VudDogMCxcbiIs" +
        "CiAgIiAgICAgICAgYWxpZ25tZW50RmFsbGJhY2tDb3VudDogMCxcbiIgKwogICIgICAgICAgIGFsaWdubWVudEZhbGxiYWNrTGFzdFJlYXNvbjogXCJcIixc" +
        "biIgKwogICIgICAgICAgIGFsaWdubWVudEZhbGxiYWNrUmVhc29uQ291bnRzOiB7fSxcbiIgKwogICIgICAgICAgIGFsaWdubWVudEZhbGxiYWNrTGFzdFNu" +
        "YXBzaG90OiBudWxsLFxuIiArCiAgIiAgICAgICAgZnVsbFJlZnJlc2hDYWxsQ291bnQ6IDAsXG4iICsKICAiICAgICAgICBmdWxsUmVmcmVzaExhc3RQZXJm" +
        "b3JtYW5jZU9yaWdpbjogXCJcIixcbiIgKwogICIgICAgICAgIGZ1bGxSZWZyZXNoTGFzdFByZWZlcnJlZEluZGV4OiAtMSxcbiIgKwogICIgICAgICAgIGZ1" +
        "bGxSZWZyZXNoTGFzdFByZXZpZXdSb3dDb3VudDogMCxcbiIgKwogICIgICAgICAgIGZ1bGxSZWZyZXNoTGFzdFJlbmRlcmVkQ291bnQ6IDAsXG4iICsKICAi" +
        "ICAgICAgICBmdWxsUmVmcmVzaExhc3RDaGlsZENvdW50OiAwLFxuIiwKICAiU3RhZ2UxNkIyIG1ldHJpY3MiKTsKICAgICAgICBzb3VyY2UgPSByZXBsYWNl" +
        "T25jZVN0cmljdChzb3VyY2UsCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5hbGlnbm1lbnRGYWxsYmFja0NvdW50ID0gMDtcbiIsCiAgIiAg" +
        "ICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5hbGlnbm1lbnRGYWxsYmFja0NvdW50ID0gMDtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNl" +
        "U3RhdGUuYWxpZ25tZW50RmFsbGJhY2tMYXN0UmVhc29uID0gXCJcIjtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuYWxpZ25tZW50" +
        "RmFsbGJhY2tSZWFzb25Db3VudHMgPSB7fTtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuYWxpZ25tZW50RmFsbGJhY2tMYXN0U25h" +
        "cHNob3QgPSBudWxsO1xuIiArCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaENhbGxDb3VudCA9IDA7XG4iICsKICAiICAg" +
        "ICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdFBlcmZvcm1hbmNlT3JpZ2luID0gXCJcIjtcbiIgKwogICIgICAgICAgIHNjcm9s" +
        "bFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hMYXN0UHJlZmVycmVkSW5kZXggPSAtMTtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3Rh" +
        "dGUuZnVsbFJlZnJlc2hMYXN0UHJldmlld1Jvd0NvdW50ID0gMDtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hM" +
        "YXN0UmVuZGVyZWRDb3VudCA9IDA7XG4iICsKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdENoaWxkQ291bnQgPSAw" +
        "O1xuIiwKICAiU3RhZ2UxNkIyIG1ldHJpYyByZXNldCIpOwogICAgICAgIHNvdXJjZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHNvdXJjZSwKICAiICAgICAgICAg" +
        "ICAgYWxpZ25tZW50RmFsbGJhY2tDb3VudDpcbiIgKwogICIgICAgICAgICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuYWxpZ25tZW50" +
        "RmFsbGJhY2tDb3VudCksXG4iICsKICAiICAgICAgICAgICAgc3BhY2VyQXBwbHlDb3VudDpcbiIsCiAgIiAgICAgICAgICAgIGFsaWdubWVudEZhbGxiYWNr" +
        "Q291bnQ6XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmFsaWdubWVudEZhbGxiYWNrQ291bnQpLFxuIiAr" +
        "CiAgIiAgICAgICAgICAgIGFsaWdubWVudEZhbGxiYWNrTGFzdFJlYXNvbjpcbiIgKwogICIgICAgICAgICAgICAgICAgU3RyaW5nKHNjcm9sbFBlcmZvcm1h" +
        "bmNlU3RhdGUuYWxpZ25tZW50RmFsbGJhY2tMYXN0UmVhc29uIHx8IFwiXCIpLFxuIiArCiAgIiAgICAgICAgICAgIGFsaWdubWVudEZhbGxiYWNrUmVhc29u" +
        "Q291bnRzOlxuIiArCiAgIiAgICAgICAgICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmFsaWdubWVudEZhbGxiYWNrUmVhc29uQ291bnRzLFxuIiAr" +
        "CiAgIiAgICAgICAgICAgIGFsaWdubWVudEZhbGxiYWNrTGFzdFNuYXBzaG90OlxuIiArCiAgIiAgICAgICAgICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0" +
        "YXRlLmFsaWdubWVudEZhbGxiYWNrTGFzdFNuYXBzaG90LFxuIiArCiAgIiAgICAgICAgICAgIGZ1bGxSZWZyZXNoQ2FsbENvdW50OlxuIiArCiAgIiAgICAg" +
        "ICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaENhbGxDb3VudCksXG4iICsKICAiICAgICAgICAgICAgZnVsbFJl" +
        "ZnJlc2hMYXN0UGVyZm9ybWFuY2VPcmlnaW46XG4iICsKICAiICAgICAgICAgICAgICAgIFN0cmluZyhzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZy" +
        "ZXNoTGFzdFBlcmZvcm1hbmNlT3JpZ2luIHx8IFwiXCIpLFxuIiArCiAgIiAgICAgICAgICAgIGZ1bGxSZWZyZXNoTGFzdFByZWZlcnJlZEluZGV4OlxuIiAr" +
        "CiAgIiAgICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaExhc3RQcmVmZXJyZWRJbmRleCksXG4iICsKICAi" +
        "ICAgICAgICAgICAgZnVsbFJlZnJlc2hMYXN0UHJldmlld1Jvd0NvdW50OlxuIiArCiAgIiAgICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFu" +
        "Y2VTdGF0ZS5mdWxsUmVmcmVzaExhc3RQcmV2aWV3Um93Q291bnQpLFxuIiArCiAgIiAgICAgICAgICAgIGZ1bGxSZWZyZXNoTGFzdFJlbmRlcmVkQ291bnQ6" +
        "XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdFJlbmRlcmVkQ291bnQpLFxuIiAr" +
        "CiAgIiAgICAgICAgICAgIGZ1bGxSZWZyZXNoTGFzdENoaWxkQ291bnQ6XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5j" +
        "ZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdENoaWxkQ291bnQpLFxuIiArCiAgIiAgICAgICAgICAgIHNwYWNlckFwcGx5Q291bnQ6XG4iLAogICJTdGFnZTE2QjIg" +
        "bWV0cmljIGNvcHkiKTsKCiAgICAgICAgb2xkQWxpZ25tZW50ID0KICAiICAgICAgICBpZiAodmlydHVhbFJlbmRlcmVkSXRlbUlkcy5sZW5ndGggIT09IGNo" +
        "aWxkQ291bnQgfHxcbiIgKwogICIgICAgICB2aXJ0dWFsUmVuZGVyZWRTaWduYXR1cmVzLmxlbmd0aCAhPT0gY2hpbGRDb3VudCB8fFxuIiArCiAgIiAgICAg" +
        "IHJlc3VsdENhcmRWaWV3cy5sZW5ndGggIT09IGNoaWxkQ291bnQgfHxcbiIgKwogICIgICAgICByZXN1bHRDYXJkSG9sZGVycy5sZW5ndGggIT09IGNoaWxk" +
        "Q291bnQgfHxcbiIgKwogICIgICAgICByZXN1bHRBY3Rpb25WaWV3cy5sZW5ndGggIT09IGNoaWxkQ291bnQpIHtcbiIgKwogICIgIHNjcm9sbFBlcmZvcm1h" +
        "bmNlU3RhdGUuYWxpZ25tZW50RmFsbGJhY2tDb3VudCArPSAxO1xuIjsKICAgICAgICBuZXdBbGlnbm1lbnQgPQogICIgICAgICAgIGlmICh2aXJ0dWFsUmVu" +
        "ZGVyZWRJdGVtSWRzLmxlbmd0aCAhPT0gY2hpbGRDb3VudCB8fFxuIiArCiAgIiAgICAgIHZpcnR1YWxSZW5kZXJlZFNpZ25hdHVyZXMubGVuZ3RoICE9PSBj" +
        "aGlsZENvdW50IHx8XG4iICsKICAiICAgICAgcmVzdWx0Q2FyZFZpZXdzLmxlbmd0aCAhPT0gY2hpbGRDb3VudCB8fFxuIiArCiAgIiAgICAgIHJlc3VsdENh" +
        "cmRIb2xkZXJzLmxlbmd0aCAhPT0gY2hpbGRDb3VudCB8fFxuIiArCiAgIiAgICAgIHJlc3VsdEFjdGlvblZpZXdzLmxlbmd0aCAhPT0gY2hpbGRDb3VudCkg" +
        "e1xuIiArCiAgIiAgdmFyIGFsaWdubWVudFJlYXNvbnMgPSBbXTtcbiIgKwogICIgIHZhciBhbGlnbm1lbnRLZXk7XG4iICsKICAiICBpZiAodmlydHVhbFJl" +
        "bmRlcmVkSXRlbUlkcy5sZW5ndGggIT09IGNoaWxkQ291bnQpIHsgYWxpZ25tZW50UmVhc29ucy5wdXNoKFwiaXRlbUlkc1wiKTsgfVxuIiArCiAgIiAgaWYg" +
        "KHZpcnR1YWxSZW5kZXJlZFNpZ25hdHVyZXMubGVuZ3RoICE9PSBjaGlsZENvdW50KSB7IGFsaWdubWVudFJlYXNvbnMucHVzaChcInNpZ25hdHVyZXNcIik7" +
        "IH1cbiIgKwogICIgIGlmIChyZXN1bHRDYXJkVmlld3MubGVuZ3RoICE9PSBjaGlsZENvdW50KSB7IGFsaWdubWVudFJlYXNvbnMucHVzaChcImNhcmRWaWV3" +
        "c1wiKTsgfVxuIiArCiAgIiAgaWYgKHJlc3VsdENhcmRIb2xkZXJzLmxlbmd0aCAhPT0gY2hpbGRDb3VudCkgeyBhbGlnbm1lbnRSZWFzb25zLnB1c2goXCJo" +
        "b2xkZXJzXCIpOyB9XG4iICsKICAiICBpZiAocmVzdWx0QWN0aW9uVmlld3MubGVuZ3RoICE9PSBjaGlsZENvdW50KSB7IGFsaWdubWVudFJlYXNvbnMucHVz" +
        "aChcImFjdGlvblZpZXdzXCIpOyB9XG4iICsKICAiICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmFsaWdubWVudEZhbGxiYWNrTGFzdFJlYXNvbiA9IGFsaWdu" +
        "bWVudFJlYXNvbnMuam9pbihcIitcIik7XG4iICsKICAiICBmb3IgKGFsaWdubWVudEtleSA9IDA7IGFsaWdubWVudEtleSA8IGFsaWdubWVudFJlYXNvbnMu" +
        "bGVuZ3RoOyBhbGlnbm1lbnRLZXkgKz0gMSkge1xuIiArCiAgIiAgICAgIGlmIChzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmFsaWdubWVudEZhbGxiYWNrUmVh" +
        "c29uQ291bnRzW2FsaWdubWVudFJlYXNvbnNbYWxpZ25tZW50S2V5XV0gPT09IHVuZGVmaW5lZCkge1xuIiArCiAgIiAgICAgICAgICBzY3JvbGxQZXJmb3Jt" +
        "YW5jZVN0YXRlLmFsaWdubWVudEZhbGxiYWNrUmVhc29uQ291bnRzW2FsaWdubWVudFJlYXNvbnNbYWxpZ25tZW50S2V5XV0gPSAwO1xuIiArCiAgIiAgICAg" +
        "IH1cbiIgKwogICIgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmFsaWdubWVudEZhbGxiYWNrUmVhc29uQ291bnRzW2FsaWdubWVudFJlYXNvbnNbYWxp" +
        "Z25tZW50S2V5XV0gKz0gMTtcbiIgKwogICIgIH1cbiIgKwogICIgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuYWxpZ25tZW50RmFsbGJhY2tMYXN0U25hcHNo" +
        "b3QgPSB7XG4iICsKICAiICAgICAgY2hpbGRDb3VudDogY2hpbGRDb3VudCxcbiIgKwogICIgICAgICBpdGVtSWRzOiB2aXJ0dWFsUmVuZGVyZWRJdGVtSWRz" +
        "Lmxlbmd0aCxcbiIgKwogICIgICAgICBzaWduYXR1cmVzOiB2aXJ0dWFsUmVuZGVyZWRTaWduYXR1cmVzLmxlbmd0aCxcbiIgKwogICIgICAgICBjYXJkVmll" +
        "d3M6IHJlc3VsdENhcmRWaWV3cy5sZW5ndGgsXG4iICsKICAiICAgICAgaG9sZGVyczogcmVzdWx0Q2FyZEhvbGRlcnMubGVuZ3RoLFxuIiArCiAgIiAgICAg" +
        "IGFjdGlvblZpZXdzOiByZXN1bHRBY3Rpb25WaWV3cy5sZW5ndGhcbiIgKwogICIgIH07XG4iICsKICAiICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmFsaWdu" +
        "bWVudEZhbGxiYWNrQ291bnQgKz0gMTtcbiI7CiAgICAgICAgc291cmNlID0gcmVwbGFjZU9uY2VTdHJpY3Qoc291cmNlLCBvbGRBbGlnbm1lbnQsIG5ld0Fs" +
        "aWdubWVudCwKICAiU3RhZ2UxNkIyIGFsaWdubWVudCBkaWFnbm9zdGljcyIpOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2Us" +
        "CiAgIiAgICAgICAgcmVidWlsZFZpcnR1YWxXaW5kb3coXG4iICsKICAiICAgICAgICAgICAgXCJmdWxsX3JlZnJlc2hcIiwgdHJ1ZSwgcHJlZmVycmVkSW5k" +
        "ZXgpO1xuIiwKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoQ2FsbENvdW50ICs9IDE7XG4iICsKICAiICAgICAgICBzY3Jv" +
        "bGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdFBlcmZvcm1hbmNlT3JpZ2luID1cbiIgKwogICIgICAgICAgICAgICBTdHJpbmcocGVyZm9ybWFu" +
        "Y2UubGFzdFJlZnJlc2hPcmlnaW4gfHwgXCJcIik7XG4iICsKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdFByZWZl" +
        "cnJlZEluZGV4ID0gTnVtYmVyKHByZWZlcnJlZEluZGV4KTtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hMYXN0" +
        "UHJldmlld1Jvd0NvdW50ID0gTnVtYmVyKHByZXZpZXdSb3dzLmxlbmd0aCk7XG4iICsKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxS" +
        "ZWZyZXNoTGFzdFJlbmRlcmVkQ291bnQgPVxuIiArCiAgIiAgICAgICAgICAgIE1hdGgubWF4KDAsIE51bWJlcih2aXJ0dWFsU3RhdGUubGFzdFJlbmRlcmVk" +
        "SW5kZXgpIC1cbiIgKwogICIgICAgICAgICAgICAgICAgTnVtYmVyKHZpcnR1YWxTdGF0ZS5maXJzdFJlbmRlcmVkSW5kZXgpICsgMSk7XG4iICsKICAiICAg" +
        "ICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdENoaWxkQ291bnQgPSB2aXJ0dWFsQ2FyZEhvc3QgPT09IG51bGwgP1xuIiArCiAg" +
        "IiAgICAgICAgICAgIC0xIDogTnVtYmVyKHZpcnR1YWxDYXJkSG9zdC5nZXRDaGlsZENvdW50KCkpO1xuIiArCiAgIiAgICAgICAgcmVidWlsZFZpcnR1YWxX" +
        "aW5kb3coXG4iICsKICAiICAgICAgICAgICAgXCJmdWxsX3JlZnJlc2hcIiwgdHJ1ZSwgcHJlZmVycmVkSW5kZXgpO1xuIiwKICAiU3RhZ2UxNkIyIGZ1bGwg" +
        "cmVmcmVzaCBkaWFnbm9zdGljcyIpOwogICAgICAgIGlmIChzb3VyY2UuaW5kZXhPZigib2xkVGFnbHMiKSA+PSAwIHx8CiAgICAgIHNvdXJjZS5pbmRleE9m" +
        "KCJNT0RVTEVfVkVSU0lPTjogNjEiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4T2YoImFsaWdubWVudEZhbGxiYWNrUmVhc29uQ291bnRzIikgPCAwIHx8" +
        "CiAgICAgIHNvdXJjZS5pbmRleE9mKCJmdWxsUmVmcmVzaENhbGxDb3VudCIpIDwgMCkgewogIHRocm93IG5ldyBFcnJvcigiU3RhZ2UxNkIyIHdpcmluZyBp" +
        "bmNvbXBsZXRlIik7CiAgICAgICAgfQogICAgICAgIHJldHVybiBzb3VyY2U7CiAgICB9CgpmdW5jdGlvbiB0cmFuc2Zvcm1TdGFnZTE2QjNTb3VyY2Uoc291" +
        "cmNlKSB7CiAgICAgICAgdmFyIGluZm87CiAgICAgICAgdmFyIHZhbHVlOwogICAgICAgIHZhciBmaW5pc2hJbmZvOwogICAgICAgIHZhciBmaW5pc2hWYWx1" +
        "ZTsKICAgICAgICB2YXIgZmluaXNoUG9zOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgIk1PRFVMRV9WRVJTSU9OOiA2" +
        "MSIsICJNT0RVTEVfVkVSU0lPTjogNjIiLAogICJTdGFnZTE2QjMgbW9kdWxlIHZlcnNpb24iKTsKCiAgICAgICAgc291cmNlID0gcmVwbGFjZU9uY2VTdHJp" +
        "Y3Qoc291cmNlLAogICIgICAgICAgIGZ1bGxSZWZyZXNoTGFzdENoaWxkQ291bnQ6IDAsXG4iLAogICIgICAgICAgIGZ1bGxSZWZyZXNoTGFzdENoaWxkQ291" +
        "bnQ6IDAsXG4iICsKICAiICAgICAgICBmdWxsUmVmcmVzaFJlcXVlc3RDb3VudDogMCxcbiIgKwogICIgICAgICAgIGZ1bGxSZWZyZXNoRHVwbGljYXRlU3Vw" +
        "cHJlc3NlZENvdW50OiAwLFxuIiArCiAgIiAgICAgICAgZnVsbFJlZnJlc2hMYXN0RGF0YUtleTogXCJcIixcbiIgKwogICIgICAgICAgIGZ1bGxSZWZyZXNo" +
        "UGVuZGluZ0RhdGFLZXk6IFwiXCIsXG4iICsKICAiICAgICAgICBmdWxsUmVmcmVzaExhc3RBcHBsaWVkRGF0YUtleTogXCJcIixcbiIgKwogICIgICAgICAg" +
        "IHZpcnR1YWxCb29ra2VlcGluZ0F0b21pY0NsZWFyQ291bnQ6IDAsXG4iLAogICJTdGFnZTE2QjMgbWV0cmljcyIpOwoKICAgICAgICBzb3VyY2UgPSByZXBs" +
        "YWNlT25jZVN0cmljdChzb3VyY2UsCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaExhc3RDaGlsZENvdW50ID0gMDtcbiIs" +
        "CiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaExhc3RDaGlsZENvdW50ID0gMDtcbiIgKwogICIgICAgICAgIHNjcm9sbFBl" +
        "cmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hSZXF1ZXN0Q291bnQgPSAwO1xuIiArCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVm" +
        "cmVzaER1cGxpY2F0ZVN1cHByZXNzZWRDb3VudCA9IDA7XG4iICsKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdERh" +
        "dGFLZXkgPSBcIlwiO1xuIiArCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaFBlbmRpbmdEYXRhS2V5ID0gXCJcIjtcbiIg" +
        "KwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hMYXN0QXBwbGllZERhdGFLZXkgPSBcIlwiO1xuIiArCiAgIiAgICAgICAg" +
        "c2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS52aXJ0dWFsQm9va2tlZXBpbmdBdG9taWNDbGVhckNvdW50ID0gMDtcbiIsCiAgIlN0YWdlMTZCMyBtZXRyaWMgcmVz" +
        "ZXQiKTsKCiAgICAgICAgc291cmNlID0gcmVwbGFjZU9uY2VTdHJpY3Qoc291cmNlLAogICIgICAgICAgICAgICBmdWxsUmVmcmVzaExhc3RDaGlsZENvdW50" +
        "OlxuIiArCiAgIiAgICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaExhc3RDaGlsZENvdW50KSxcbiIgKwog" +
        "ICIgICAgICAgICAgICBzcGFjZXJBcHBseUNvdW50OlxuIiwKICAiICAgICAgICAgICAgZnVsbFJlZnJlc2hMYXN0Q2hpbGRDb3VudDpcbiIgKwogICIgICAg" +
        "ICAgICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hMYXN0Q2hpbGRDb3VudCksXG4iICsKICAiICAgICAgICAgICAg" +
        "ZnVsbFJlZnJlc2hSZXF1ZXN0Q291bnQ6XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNo" +
        "UmVxdWVzdENvdW50KSxcbiIgKwogICIgICAgICAgICAgICBmdWxsUmVmcmVzaER1cGxpY2F0ZVN1cHByZXNzZWRDb3VudDpcbiIgKwogICIgICAgICAgICAg" +
        "ICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hEdXBsaWNhdGVTdXBwcmVzc2VkQ291bnQpLFxuIiArCiAgIiAgICAgICAg" +
        "ICAgIGZ1bGxSZWZyZXNoTGFzdERhdGFLZXk6XG4iICsKICAiICAgICAgICAgICAgICAgIFN0cmluZyhzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZy" +
        "ZXNoTGFzdERhdGFLZXkgfHwgXCJcIiksXG4iICsKICAiICAgICAgICAgICAgZnVsbFJlZnJlc2hQZW5kaW5nRGF0YUtleTpcbiIgKwogICIgICAgICAgICAg" +
        "ICAgICAgU3RyaW5nKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hQZW5kaW5nRGF0YUtleSB8fCBcIlwiKSxcbiIgKwogICIgICAgICAgICAg" +
        "ICBmdWxsUmVmcmVzaExhc3RBcHBsaWVkRGF0YUtleTpcbiIgKwogICIgICAgICAgICAgICAgICAgU3RyaW5nKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVs" +
        "bFJlZnJlc2hMYXN0QXBwbGllZERhdGFLZXkgfHwgXCJcIiksXG4iICsKICAiICAgICAgICAgICAgdmlydHVhbEJvb2trZWVwaW5nQXRvbWljQ2xlYXJDb3Vu" +
        "dDpcbiIgKwogICIgICAgICAgICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUudmlydHVhbEJvb2trZWVwaW5nQXRvbWljQ2xlYXJDb3Vu" +
        "dCksXG4iICsKICAiICAgICAgICAgICAgc3BhY2VyQXBwbHlDb3VudDpcbiIsCiAgIlN0YWdlMTZCMyBtZXRyaWMgY29weSIpOwoKICAgICAgICBpbmZvID0g" +
        "c2VjdGlvbihzb3VyY2UsCiAgIiAgICBmdW5jdGlvbiByZWZyZXNoUmVzdWx0c09uTWFpbigpIHsiLAogICJcbiAgICBmdW5jdGlvbiAiLAogICJTdGFnZTE2" +
        "QjMgcmVmcmVzaCByZXN1bHRzIik7CiAgICAgICAgdmFsdWUgPSBpbmZvLnRleHQ7CiAgICAgICAgdmFsdWUgPSByZXBsYWNlT25jZVN0cmljdCh2YWx1ZSwK" +
        "ICAiICAgICAgICB2YXIgcHJlZmVycmVkSW5kZXg7XG4iICsKICAiICAgICAgICBpZiAocmVzdWx0Q29udGFpbmVyID09PSBudWxsKSB7IHJldHVybiBmYWxz" +
        "ZTsgfVxuIiwKICAiICAgICAgICB2YXIgcHJlZmVycmVkSW5kZXg7XG4iICsKICAiICAgICAgICB2YXIgZnVsbFJlZnJlc2hEYXRhS2V5O1xuIiArCiAgIiAg" +
        "ICAgICAgaWYgKHJlc3VsdENvbnRhaW5lciA9PT0gbnVsbCkgeyByZXR1cm4gZmFsc2U7IH1cbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3Rh" +
        "dGUuZnVsbFJlZnJlc2hSZXF1ZXN0Q291bnQgKz0gMTtcbiIgKwogICIgICAgICAgIGZ1bGxSZWZyZXNoRGF0YUtleSA9IFtcbiIgKwogICIgICAgICAgICAg" +
        "ICBTdHJpbmcoTnVtYmVyKHBhbmVsRGF0YVZlcnNpb24gfHwgMCkpLFxuIiArCiAgIiAgICAgICAgICAgIFN0cmluZyhOdW1iZXIocGFnaW5hdGlvblN0YXRl" +
        "LnF1ZXJ5R2VuZXJhdGlvbiB8fCAwKSksXG4iICsKICAiICAgICAgICAgICAgU3RyaW5nKE51bWJlcihzZWFyY2hHZW5lcmF0aW9uIHx8IDApKSxcbiIgKwog" +
        "ICIgICAgICAgICAgICBTdHJpbmcoTnVtYmVyKHByZXZpZXdSb3dzLmxlbmd0aCB8fCAwKSksXG4iICsKICAiICAgICAgICAgICAgcHJldmlld1Jvd3MubGVu" +
        "Z3RoID4gMCA/IFN0cmluZyhOdW1iZXIocHJldmlld1Jvd3NbMF0uaWQpKSA6IFwiLVwiLFxuIiArCiAgIiAgICAgICAgICAgIHByZXZpZXdSb3dzLmxlbmd0" +
        "aCA+IDAgPyBTdHJpbmcoTnVtYmVyKHByZXZpZXdSb3dzW3ByZXZpZXdSb3dzLmxlbmd0aCAtIDFdLmlkKSkgOiBcIi1cIixcbiIgKwogICIgICAgICAgICAg" +
        "ICByb290TW9kZSA/IFwiMVwiIDogXCIwXCJcbiIgKwogICIgICAgICAgIF0uam9pbihcInxcIik7XG4iICsKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5j" +
        "ZVN0YXRlLmZ1bGxSZWZyZXNoTGFzdERhdGFLZXkgPSBmdWxsUmVmcmVzaERhdGFLZXk7XG4iICsKICAiICAgICAgICBpZiAoU3RyaW5nKHBlcmZvcm1hbmNl" +
        "Lmxhc3RSZWZyZXNoT3JpZ2luIHx8IFwiXCIpID09PSBcInBhbmVsX2ZpcnN0X2NvbnRlbnRcIiAmJlxuIiArCiAgIiAgICAgICAgICAgICAgICBzdGF0ZS5j" +
        "b250ZW50UmVhZHkgPT09IHRydWUgJiZcbiIgKwogICIgICAgICAgICAgICAgICAgdmlydHVhbENhcmRIb3N0ICE9PSBudWxsICYmXG4iICsKICAiICAgICAg" +
        "ICAgICAgICAgIE51bWJlcih2aXJ0dWFsQ2FyZEhvc3QuZ2V0Q2hpbGRDb3VudCgpKSA+IDAgJiZcbiIgKwogICIgICAgICAgICAgICAgICAgU3RyaW5nKHNj" +
        "cm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hMYXN0QXBwbGllZERhdGFLZXkgfHwgXCJcIikgPT09XG4iICsKICAiICAgICAgICAgICAgICAgICAg" +
        "ICBmdWxsUmVmcmVzaERhdGFLZXkpIHtcbiIgKwogICIgICAgICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoRHVwbGljYXRlU3Vw" +
        "cHJlc3NlZENvdW50ICs9IDE7XG4iICsKICAiICAgICAgICAgICAgcmV0dXJuIGZhbHNlO1xuIiArCiAgIiAgICAgICAgfVxuIiArCiAgIiAgICAgICAgc2Ny" +
        "b2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaFBlbmRpbmdEYXRhS2V5ID0gZnVsbFJlZnJlc2hEYXRhS2V5O1xuIiwKICAiU3RhZ2UxNkIzIGR1cGxp" +
        "Y2F0ZSBndWFyZCIpOwoKICAgICAgICB2YWx1ZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHZhbHVlLAogICIgICAgICAgIHJlc3VsdENhcmRWaWV3cyA9IFtdO1xu" +
        "IiArCiAgIiAgICAgICAgcmVzdWx0Q2FyZEhvbGRlcnMgPSBbXTtcbiIgKwogICIgICAgICAgIHJlc3VsdEFjdGlvblZpZXdzID0gW107XG4iICsKICAiICAg" +
        "ICAgICByZXN1bHRUYWdNYXAgPSB7fTtcbiIsCiAgIiAgICAgICAgcmVzdWx0Q2FyZFZpZXdzID0gW107XG4iICsKICAiICAgICAgICByZXN1bHRDYXJkSG9s" +
        "ZGVycyA9IFtdO1xuIiArCiAgIiAgICAgICAgcmVzdWx0QWN0aW9uVmlld3MgPSBbXTtcbiIgKwogICIgICAgICAgIHZpcnR1YWxSZW5kZXJlZEl0ZW1JZHMg" +
        "PSBbXTtcbiIgKwogICIgICAgICAgIHZpcnR1YWxSZW5kZXJlZFNpZ25hdHVyZXMgPSBbXTtcbiIgKwogICIgICAgICAgIHZpcnR1YWxTdGF0ZS5maXJzdFJl" +
        "bmRlcmVkSW5kZXggPSAwO1xuIiArCiAgIiAgICAgICAgdmlydHVhbFN0YXRlLmxhc3RSZW5kZXJlZEluZGV4ID0gLTE7XG4iICsKICAiICAgICAgICBzY3Jv" +
        "bGxQZXJmb3JtYW5jZVN0YXRlLnZpcnR1YWxCb29ra2VlcGluZ0F0b21pY0NsZWFyQ291bnQgKz0gMTtcbiIgKwogICIgICAgICAgIHJlc3VsdFRhZ01hcCA9" +
        "IHt9O1xuIiwKICAiU3RhZ2UxNkIzIGF0b21pYyB2aXJ0dWFsIGNsZWFyIik7CiAgICAgICAgc291cmNlID0gcmVwbGFjZVNlY3Rpb24oc291cmNlLCBpbmZv" +
        "LCB2YWx1ZSk7CgogICAgICAgIGZpbmlzaEluZm8gPSBzZWN0aW9uKHNvdXJjZSwKICAiICAgIGZ1bmN0aW9uIGZpbmlzaFJlc3VsdFJlbmRlcihnZW5lcmF0" +
        "aW9uLCBjb2xvcnMpIHsiLAogICJcbiAgICBmdW5jdGlvbiAiLAogICJTdGFnZTE2QjMgZmluaXNoIHJlbmRlciIpOwogICAgICAgIGZpbmlzaFZhbHVlID0g" +
        "ZmluaXNoSW5mby50ZXh0OwogICAgICAgIGZpbmlzaFBvcyA9IGZpbmlzaFZhbHVlLmxhc3RJbmRleE9mKCIgICAgICAgIHJldHVybiB0cnVlOyIpOwogICAg" +
        "ICAgIGlmIChmaW5pc2hQb3MgPCAwKSB7CiAgdGhyb3cgbmV3IEVycm9yKCJTdGFnZTE2QjMgZmluaXNoIHN1Y2Nlc3MgcmV0dXJuIG1pc3NpbmciKTsKICAg" +
        "ICAgICB9CiAgICAgICAgZmluaXNoVmFsdWUgPSBmaW5pc2hWYWx1ZS5zdWJzdHJpbmcoMCwgZmluaXNoUG9zKSArCiAgIiAgICAgICAgaWYgKFN0cmluZyhz" +
        "Y3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoUGVuZGluZ0RhdGFLZXkgfHwgXCJcIikubGVuZ3RoID4gMCkge1xuIiArCiAgIiAgICAgICAgICAg" +
        "IHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hMYXN0QXBwbGllZERhdGFLZXkgPVxuIiArCiAgIiAgICAgICAgICAgICAgICBTdHJpbmcoc2Ny" +
        "b2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaFBlbmRpbmdEYXRhS2V5KTtcbiIgKwogICIgICAgICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRl" +
        "LmZ1bGxSZWZyZXNoUGVuZGluZ0RhdGFLZXkgPSBcIlwiO1xuIiArCiAgIiAgICAgICAgfVxuIiArCiAgZmluaXNoVmFsdWUuc3Vic3RyaW5nKGZpbmlzaFBv" +
        "cyk7CiAgICAgICAgc291cmNlID0gcmVwbGFjZVNlY3Rpb24oc291cmNlLCBmaW5pc2hJbmZvLCBmaW5pc2hWYWx1ZSk7CgogICAgICAgIGlmIChzb3VyY2Uu" +
        "aW5kZXhPZigib2xkVGFnbHMiKSA+PSAwIHx8CiAgICAgIHNvdXJjZS5pbmRleE9mKCJuZXdUYWdscyIpID49IDAgfHwKICAgICAgc291cmNlLmluZGV4T2Yo" +
        "Ik1PRFVMRV9WRVJTSU9OOiA2MiIpIDwgMCB8fAogICAgICBzb3VyY2UuaW5kZXhPZigidmlydHVhbEJvb2trZWVwaW5nQXRvbWljQ2xlYXJDb3VudCIpIDwg" +
        "MCB8fAogICAgICBzb3VyY2UuaW5kZXhPZigiZnVsbFJlZnJlc2hEdXBsaWNhdGVTdXBwcmVzc2VkQ291bnQiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4" +
        "T2YoInZpcnR1YWxSZW5kZXJlZEl0ZW1JZHMgPSBbXTtcbiAgICAgICAgdmlydHVhbFJlbmRlcmVkU2lnbmF0dXJlcyA9IFtdO1xuICAgICAgICB2aXJ0dWFs" +
        "U3RhdGUuZmlyc3RSZW5kZXJlZEluZGV4ID0gMDtcbiAgICAgICAgdmlydHVhbFN0YXRlLmxhc3RSZW5kZXJlZEluZGV4ID0gLTE7IikgPCAwKSB7CiAgdGhy" +
        "b3cgbmV3IEVycm9yKCJTdGFnZTE2QjMgd2lyaW5nIGluY29tcGxldGUiKTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuIHNvdXJjZTsKICAgIH0KCmZ1bmN0" +
        "aW9uIHRyYW5zZm9ybVN0YWdlMTZCNFNvdXJjZShzb3VyY2UpIHsKICAgICAgICB2YXIgaW5mbzsKICAgICAgICB2YXIgdmFsdWU7CgogICAgICAgIHNvdXJj" +
        "ZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHNvdXJjZSwKICAiTU9EVUxFX1ZFUlNJT046IDYyIiwgIk1PRFVMRV9WRVJTSU9OOiA2MyIsCiAgIlN0YWdlMTZCNCBt" +
        "b2R1bGUgdmVyc2lvbiIpOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgIiAgICAgICAgdmlydHVhbEJvb2trZWVwaW5n" +
        "QXRvbWljQ2xlYXJDb3VudDogMCxcbiIsCiAgIiAgICAgICAgdmlydHVhbEJvb2trZWVwaW5nQXRvbWljQ2xlYXJDb3VudDogMCxcbiIgKwogICIgICAgICAg" +
        "IGZ1bGxSZWZyZXNoU2FtcGxlczogW10sXG4iLAogICJTdGFnZTE2QjQgc2FtcGxlIG1ldHJpYyIpOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0" +
        "cmljdChzb3VyY2UsCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS52aXJ0dWFsQm9va2tlZXBpbmdBdG9taWNDbGVhckNvdW50ID0gMDtcbiIs" +
        "CiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS52aXJ0dWFsQm9va2tlZXBpbmdBdG9taWNDbGVhckNvdW50ID0gMDtcbiIgKwogICIgICAgICAg" +
        "IHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hTYW1wbGVzID0gW107XG4iLAogICJTdGFnZTE2QjQgc2FtcGxlIHJlc2V0Iik7CgogICAgICAg" +
        "IHNvdXJjZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHNvdXJjZSwKICAiICAgICAgICAgICAgdmlydHVhbEJvb2trZWVwaW5nQXRvbWljQ2xlYXJDb3VudDpcbiIg" +
        "KwogICIgICAgICAgICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUudmlydHVhbEJvb2trZWVwaW5nQXRvbWljQ2xlYXJDb3VudCksXG4i" +
        "ICsKICAiICAgICAgICAgICAgc3BhY2VyQXBwbHlDb3VudDpcbiIsCiAgIiAgICAgICAgICAgIHZpcnR1YWxCb29ra2VlcGluZ0F0b21pY0NsZWFyQ291bnQ6" +
        "XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLnZpcnR1YWxCb29ra2VlcGluZ0F0b21pY0NsZWFyQ291bnQp" +
        "LFxuIiArCiAgIiAgICAgICAgICAgIGZ1bGxSZWZyZXNoU2FtcGxlczpcbiIgKwogICIgICAgICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5m" +
        "dWxsUmVmcmVzaFNhbXBsZXMuc2xpY2UoMCksXG4iICsKICAiICAgICAgICAgICAgc3BhY2VyQXBwbHlDb3VudDpcbiIsCiAgIlN0YWdlMTZCNCBzYW1wbGUg" +
        "Y29weSIpOwoKICAgICAgICBpbmZvID0gc2VjdGlvbihzb3VyY2UsCiAgIiAgICBmdW5jdGlvbiByZWJpbmRSZXN1bHRDYXJkSG9sZGVyKGhvbGRlciwgcm93" +
        "LCBjb2xvcnMpIHsiLAogICJcbiAgICBmdW5jdGlvbiAiLAogICJTdGFnZTE2QjQgaG9sZGVyIHJlYmluZCIpOwogICAgICAgIHZhbHVlID0gaW5mby50ZXh0" +
        "OwogICAgICAgIHZhbHVlID0gcmVwbGFjZU9uY2VTdHJpY3QodmFsdWUsCiAgIiAgICAgICAgICAgIGhvbGRlci50YWdCYWRnZS5zZXRUZXh0Q29sb3IobmV3" +
        "VGFncy5sZW5ndGggPiAwID8gdGFnQ29sb3JUZXh0KG5ld1RhZ3NbMF0sIGNvbG9ycy5hY2NlbnRTdHJvbmcpIDogY29sb3JzLnRleHRUZXJ0aWFyeSk7XG4i" +
        "LAogICIgICAgICAgICAgICBob2xkZXIudGFnQmFkZ2VbXCJzZXRUZXh0Q29sb3IoaW50KVwiXSgiICsKICAic2FmZUNvbG9ySW50KG5ld1RhZ3MubGVuZ3Ro" +
        "ID4gMCA/ICIgKwogICJ0YWdDb2xvclRleHQobmV3VGFnc1swXSwgY29sb3JzLmFjY2VudFN0cm9uZykgOiAiICsKICAiY29sb3JzLnRleHRUZXJ0aWFyeSwg" +
        "Y29sb3JzLnRleHRUZXJ0aWFyeSkpO1xuIiwKICAiU3RhZ2UxNkI0IHRhZyBjb2xvciBpbnQiKTsKICAgICAgICBzb3VyY2UgPSByZXBsYWNlU2VjdGlvbihz" +
        "b3VyY2UsIGluZm8sIHZhbHVlKTsKCiAgICAgICAgaW5mbyA9IHNlY3Rpb24oc291cmNlLAogICIgICAgZnVuY3Rpb24gcmVmcmVzaFJlc3VsdHNPbk1haW4o" +
        "KSB7IiwKICAiXG4gICAgZnVuY3Rpb24gIiwKICAiU3RhZ2UxNkI0IHJlZnJlc2ggcmVzdWx0cyIpOwogICAgICAgIHZhbHVlID0gaW5mby50ZXh0OwogICAg" +
        "ICAgIHZhbHVlID0gcmVwbGFjZU9uY2VTdHJpY3QodmFsdWUsCiAgIiAgICAgICAgdmFyIGZ1bGxSZWZyZXNoRGF0YUtleTtcbiIsCiAgIiAgICAgICAgdmFy" +
        "IGZ1bGxSZWZyZXNoRGF0YUtleTtcbiIgKwogICIgICAgICAgIHZhciBmdWxsUmVmcmVzaFNhbXBsZTtcbiIsCiAgIlN0YWdlMTZCNCBzYW1wbGUgdmFyaWFi" +
        "bGUiKTsKICAgICAgICB2YWx1ZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHZhbHVlLAogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJl" +
        "c2hMYXN0RGF0YUtleSA9IGZ1bGxSZWZyZXNoRGF0YUtleTtcbiIsCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaExhc3RE" +
        "YXRhS2V5ID0gZnVsbFJlZnJlc2hEYXRhS2V5O1xuIiArCiAgIiAgICAgICAgZnVsbFJlZnJlc2hTYW1wbGUgPSB7XG4iICsKICAiICAgICAgICAgICAgb3Jp" +
        "Z2luOiBTdHJpbmcocGVyZm9ybWFuY2UubGFzdFJlZnJlc2hPcmlnaW4gfHwgXCJcIiksXG4iICsKICAiICAgICAgICAgICAgZGF0YUtleTogU3RyaW5nKGZ1" +
        "bGxSZWZyZXNoRGF0YUtleSksXG4iICsKICAiICAgICAgICAgICAgcGFuZWxEYXRhVmVyc2lvbjogTnVtYmVyKHBhbmVsRGF0YVZlcnNpb24gfHwgMCksXG4i" +
        "ICsKICAiICAgICAgICAgICAgcXVlcnlHZW5lcmF0aW9uOiBOdW1iZXIocGFnaW5hdGlvblN0YXRlLnF1ZXJ5R2VuZXJhdGlvbiB8fCAwKSxcbiIgKwogICIg" +
        "ICAgICAgICAgICBzZWFyY2hHZW5lcmF0aW9uOiBOdW1iZXIoc2VhcmNoR2VuZXJhdGlvbiB8fCAwKSxcbiIgKwogICIgICAgICAgICAgICBwcmV2aWV3Um93" +
        "Q291bnQ6IE51bWJlcihwcmV2aWV3Um93cy5sZW5ndGggfHwgMCksXG4iICsKICAiICAgICAgICAgICAgZmlyc3RJZDogcHJldmlld1Jvd3MubGVuZ3RoID4g" +
        "MCA/IE51bWJlcihwcmV2aWV3Um93c1swXS5pZCkgOiAtMSxcbiIgKwogICIgICAgICAgICAgICBsYXN0SWQ6IHByZXZpZXdSb3dzLmxlbmd0aCA+IDAgPyBO" +
        "dW1iZXIocHJldmlld1Jvd3NbcHJldmlld1Jvd3MubGVuZ3RoIC0gMV0uaWQpIDogLTEsXG4iICsKICAiICAgICAgICAgICAgY29udGVudFJlYWR5OiBzdGF0" +
        "ZS5jb250ZW50UmVhZHkgPT09IHRydWUsXG4iICsKICAiICAgICAgICAgICAgY2hpbGRDb3VudDogdmlydHVhbENhcmRIb3N0ID09PSBudWxsID8gLTEgOiBO" +
        "dW1iZXIodmlydHVhbENhcmRIb3N0LmdldENoaWxkQ291bnQoKSksXG4iICsKICAiICAgICAgICAgICAgcmVuZGVyR2VuZXJhdGlvbjogTnVtYmVyKHJlbmRl" +
        "ckdlbmVyYXRpb24gfHwgMCksXG4iICsKICAiICAgICAgICAgICAgYXRNczogTnVtYmVyKFN5c3RlbS5jdXJyZW50VGltZU1pbGxpcygpKSxcbiIgKwogICIg" +
        "ICAgICAgICAgICBjYWxsZWQ6IGZhbHNlLFxuIiArCiAgIiAgICAgICAgICAgIHN1cHByZXNzZWQ6IGZhbHNlXG4iICsKICAiICAgICAgICB9O1xuIiArCiAg" +
        "IiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaFNhbXBsZXMucHVzaChmdWxsUmVmcmVzaFNhbXBsZSk7XG4iICsKICAiICAgICAg" +
        "ICB3aGlsZSAoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaFNhbXBsZXMubGVuZ3RoID4gOCkge1xuIiArCiAgIiAgICAgICAgICAgIHNjcm9s" +
        "bFBlcmZvcm1hbmNlU3RhdGUuZnVsbFJlZnJlc2hTYW1wbGVzLnNoaWZ0KCk7XG4iICsKICAiICAgICAgICB9XG4iLAogICJTdGFnZTE2QjQgc2FtcGxlIGNh" +
        "cHR1cmUiKTsKICAgICAgICB2YWx1ZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHZhbHVlLAogICIgICAgICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1" +
        "bGxSZWZyZXNoRHVwbGljYXRlU3VwcHJlc3NlZENvdW50ICs9IDE7XG4iICsKICAiICAgICAgICAgICAgcmV0dXJuIGZhbHNlO1xuIiwKICAiICAgICAgICAg" +
        "ICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5mdWxsUmVmcmVzaER1cGxpY2F0ZVN1cHByZXNzZWRDb3VudCArPSAxO1xuIiArCiAgIiAgICAgICAgICAgIGZ1" +
        "bGxSZWZyZXNoU2FtcGxlLnN1cHByZXNzZWQgPSB0cnVlO1xuIiArCiAgIiAgICAgICAgICAgIHJldHVybiBmYWxzZTtcbiIsCiAgIlN0YWdlMTZCNCBzYW1w" +
        "bGUgc3VwcHJlc3NlZCIpOwogICAgICAgIHZhbHVlID0gcmVwbGFjZU9uY2VTdHJpY3QodmFsdWUsCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0" +
        "ZS5mdWxsUmVmcmVzaENhbGxDb3VudCArPSAxO1xuIiwKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmZ1bGxSZWZyZXNoQ2FsbENvdW50ICs9" +
        "IDE7XG4iICsKICAiICAgICAgICBmdWxsUmVmcmVzaFNhbXBsZS5jYWxsZWQgPSB0cnVlO1xuIiwKICAiU3RhZ2UxNkI0IHNhbXBsZSBjYWxsZWQiKTsKICAg" +
        "ICAgICBzb3VyY2UgPSByZXBsYWNlU2VjdGlvbihzb3VyY2UsIGluZm8sIHZhbHVlKTsKCiAgICAgICAgaWYgKHNvdXJjZS5pbmRleE9mKCJNT0RVTEVfVkVS" +
        "U0lPTjogNjMiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4T2YoImZ1bGxSZWZyZXNoU2FtcGxlcyIpIDwgMCB8fAogICAgICBzb3VyY2UuaW5kZXhPZigi" +
        "ZnVsbFJlZnJlc2hTYW1wbGUuY2FsbGVkID0gdHJ1ZSIpIDwgMCB8fAogICAgICBzb3VyY2UuaW5kZXhPZigiZnVsbFJlZnJlc2hTYW1wbGUuc3VwcHJlc3Nl" +
        "ZCA9IHRydWUiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4T2YoImhvbGRlci50YWdCYWRnZVtcInNldFRleHRDb2xvcihpbnQpXCJdIikgPCAwIHx8CiAg" +
        "ICAgIHNvdXJjZS5pbmRleE9mKCJzYWZlQ29sb3JJbnQobmV3VGFncy5sZW5ndGggPiAwIikgPCAwKSB7CiAgdGhyb3cgbmV3IEVycm9yKCJTdGFnZTE2QjQg" +
        "d2lyaW5nIGluY29tcGxldGUiKTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuIHNvdXJjZTsKICAgIH0KCmZ1bmN0aW9uIHJlcGxhY2VBbGxTdGFnZTE2Qyhz" +
        "b3VyY2UsIG9sZFRleHQsIG5ld1RleHQsIGV4cGVjdGVkQ291bnQsIGxhYmVsKSB7CiAgICAgICAgdmFyIHBhcnRzID0gU3RyaW5nKHNvdXJjZSkuc3BsaXQo" +
        "U3RyaW5nKG9sZFRleHQpKTsKICAgICAgICB2YXIgY291bnQgPSBwYXJ0cy5sZW5ndGggLSAxOwogICAgICAgIGlmIChjb3VudCAhPT0gTnVtYmVyKGV4cGVj" +
        "dGVkQ291bnQpKSB7CiAgdGhyb3cgbmV3IEVycm9yKFN0cmluZyhsYWJlbCB8fCAiU3RhZ2UxNkMgcmVwbGFjZSIpICsKICAgICAgIiBleHBlY3RlZCAiICsg" +
        "U3RyaW5nKGV4cGVjdGVkQ291bnQpICsgIiBnb3QgIiArIFN0cmluZyhjb3VudCkpOwogICAgICAgIH0KICAgICAgICByZXR1cm4gcGFydHMuam9pbihTdHJp" +
        "bmcobmV3VGV4dCkpOwogICAgfQoKICAgIGZ1bmN0aW9uIHRyYW5zZm9ybVN0YWdlMTZDU291cmNlKHNvdXJjZSkgewogICAgICAgIHZhciBoZWxwZXJUZXh0" +
        "OwogICAgICAgIHZhciBvbGRUYWtlOwogICAgICAgIHZhciBuZXdUYWtlOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAg" +
        "Ik1PRFVMRV9WRVJTSU9OOiA2MyIsICJNT0RVTEVfVkVSU0lPTjogNjQiLAogICJTdGFnZTE2QyBtb2R1bGUgdmVyc2lvbiIpOwoKICAgICAgICBzb3VyY2Ug" +
        "PSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgIiAgICAgICAgaG9sZGVyUmVjeWNsZURpc2NhcmRDb3VudDogMCxcbiIsCiAgIiAgICAgICAgaG9sZGVy" +
        "UmVjeWNsZURpc2NhcmRDb3VudDogMCxcbiIgKwogICIgICAgICAgIGhvbGRlclJlY3ljbGVLZXlIaXRDb3VudDogMCxcbiIgKwogICIgICAgICAgIGhvbGRl" +
        "clJlY3ljbGVLZXlNaXNzQ291bnQ6IDAsXG4iICsKICAiICAgICAgICBob2xkZXJSZWN5Y2xlUG9vbFNjYW5Db3VudDogMCxcbiIgKwogICIgICAgICAgIGhv" +
        "bGRlclJlY3ljbGVQb29sUGVha0NvdW50OiAwLFxuIiwKICAiU3RhZ2UxNkMgbWV0cmljcyIpOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmlj" +
        "dChzb3VyY2UsCiAgIiAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlRGlzY2FyZENvdW50ID0gMDtcbiIsCiAgIiAgICAgICAg" +
        "c2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlRGlzY2FyZENvdW50ID0gMDtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3Rh" +
        "dGUuaG9sZGVyUmVjeWNsZUtleUhpdENvdW50ID0gMDtcbiIgKwogICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZUtleU1p" +
        "c3NDb3VudCA9IDA7XG4iICsKICAiICAgICAgICBzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlY3ljbGVQb29sU2NhbkNvdW50ID0gMDtcbiIgKwog" +
        "ICIgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZVBvb2xQZWFrQ291bnQgPSAwO1xuIiwKICAiU3RhZ2UxNkMgbWV0cmljIHJl" +
        "c2V0Iik7CgogICAgICAgIHNvdXJjZSA9IHJlcGxhY2VPbmNlU3RyaWN0KHNvdXJjZSwKICAiICAgICAgICAgICAgaG9sZGVyUmVjeWNsZURpc2NhcmRDb3Vu" +
        "dDpcbiIgKwogICIgICAgICAgICAgICAgICAgTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZURpc2NhcmRDb3VudCksXG4iICsK" +
        "ICAiICAgICAgICAgICAgaG9sZGVyUmViaW5kQ291bnQ6XG4iLAogICIgICAgICAgICAgICBob2xkZXJSZWN5Y2xlRGlzY2FyZENvdW50OlxuIiArCiAgIiAg" +
        "ICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlRGlzY2FyZENvdW50KSxcbiIgKwogICIgICAgICAgICAg" +
        "ICBob2xkZXJSZWN5Y2xlS2V5SGl0Q291bnQ6XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJl" +
        "Y3ljbGVLZXlIaXRDb3VudCksXG4iICsKICAiICAgICAgICAgICAgaG9sZGVyUmVjeWNsZUtleU1pc3NDb3VudDpcbiIgKwogICIgICAgICAgICAgICAgICAg" +
        "TnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZUtleU1pc3NDb3VudCksXG4iICsKICAiICAgICAgICAgICAgaG9sZGVyUmVjeWNs" +
        "ZVBvb2xTY2FuQ291bnQ6XG4iICsKICAiICAgICAgICAgICAgICAgIE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlY3ljbGVQb29sU2Nh" +
        "bkNvdW50KSxcbiIgKwogICIgICAgICAgICAgICBob2xkZXJSZWN5Y2xlUG9vbFBlYWtDb3VudDpcbiIgKwogICIgICAgICAgICAgICAgICAgTnVtYmVyKHNj" +
        "cm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZVBvb2xQZWFrQ291bnQpLFxuIiArCiAgIiAgICAgICAgICAgIGhvbGRlclJlYmluZENvdW50Olxu" +
        "IiwKICAiU3RhZ2UxNkMgbWV0cmljIGNvcHkiKTsKCiAgICAgICAgaGVscGVyVGV4dCA9CiAgIiAgICBmdW5jdGlvbiByZXN1bHRDYXJkUmVjeWNsZUtleUZv" +
        "clJvdyhyb3cpIHtcbiIgKwogICIgICAgICAgIHZhciB0YWdzID0gdGFnc0ZvclJlc3VsdChyb3cpO1xuIiArCiAgIiAgICAgICAgdmFyIHNlbGVjdGVkID0g" +
        "U0VMRUNUSU9OX0VOQUJMRUQgJiYgc2VsZWN0ZWRJdGVtSWQgIT09IG51bGwgJiZcbiIgKwogICIgICAgICAgICAgICBOdW1iZXIoc2VsZWN0ZWRJdGVtSWQp" +
        "ID09PSBOdW1iZXIocm93LmlkKTtcbiIgKwogICIgICAgICAgIHJldHVybiBbXG4iICsKICAiICAgICAgICAgICAgU3RyaW5nKHJvdy5zb3VyY2VfcGFja2Fn" +
        "ZSB8fCBcIlwiKSxcbiIgKwogICIgICAgICAgICAgICBOdW1iZXIocm93LmlzX3Bpbm5lZCB8fCAwKSA9PT0gMSA/IFwiMVwiIDogXCIwXCIsXG4iICsKICAi" +
        "ICAgICAgICAgICAgc2VsZWN0ZWQgPyBcIjFcIiA6IFwiMFwiLFxuIiArCiAgIiAgICAgICAgICAgIHRhZ3MubGVuZ3RoID4gMCA/IFwiMVwiIDogXCIwXCJc" +
        "biIgKwogICIgICAgICAgIF0uam9pbihcIlxcdTAwMWZcIik7XG4iICsKICAiICAgIH1cblxuIiArCiAgIiAgICBmdW5jdGlvbiByZXN1bHRDYXJkUmVjeWNs" +
        "ZUtleUZvckhvbGRlcihob2xkZXIpIHtcbiIgKwogICIgICAgICAgIHZhciByb3c7XG4iICsKICAiICAgICAgICB2YXIgdGFncztcbiIgKwogICIgICAgICAg" +
        "IGlmIChob2xkZXIgPT09IG51bGwgfHwgaG9sZGVyID09PSB1bmRlZmluZWQgfHxcbiIgKwogICIgICAgICAgICAgICAgICAgaG9sZGVyLnJvdyA9PT0gbnVs" +
        "bCB8fCBob2xkZXIucm93ID09PSB1bmRlZmluZWQpIHtcbiIgKwogICIgICAgICAgICAgICByZXR1cm4gXCJcIjtcbiIgKwogICIgICAgICAgIH1cbiIgKwog" +
        "ICIgICAgICAgIHJvdyA9IGhvbGRlci5yb3c7XG4iICsKICAiICAgICAgICB0YWdzID0gdGFnc0ZvclJlc3VsdChyb3cpO1xuIiArCiAgIiAgICAgICAgcmV0" +
        "dXJuIFtcbiIgKwogICIgICAgICAgICAgICBTdHJpbmcoaG9sZGVyLnNvdXJjZVBhY2thZ2UgfHwgcm93LnNvdXJjZV9wYWNrYWdlIHx8IFwiXCIpLFxuIiAr" +
        "CiAgIiAgICAgICAgICAgIGhvbGRlci5waW5uZWQgPT09IHRydWUgPyBcIjFcIiA6IFwiMFwiLFxuIiArCiAgIiAgICAgICAgICAgIGhvbGRlci5zZWxlY3Rl" +
        "ZCA9PT0gdHJ1ZSA/IFwiMVwiIDogXCIwXCIsXG4iICsKICAiICAgICAgICAgICAgdGFncy5sZW5ndGggPiAwID8gXCIxXCIgOiBcIjBcIlxuIiArCiAgIiAg" +
        "ICAgICAgXS5qb2luKFwiXFx1MDAxZlwiKTtcbiIgKwogICIgICAgfVxuXG4iICsKICAiICAgIGZ1bmN0aW9uIHRha2VDb21wYXRpYmxlUmVjeWNsZUhvbGRl" +
        "cihwb29sLCByb3cpIHtcbiIgKwogICIgICAgICAgIHZhciBrZXkgPSByZXN1bHRDYXJkUmVjeWNsZUtleUZvclJvdyhyb3cpO1xuIiArCiAgIiAgICAgICAg" +
        "dmFyIGluZGV4O1xuIiArCiAgIiAgICAgICAgaWYgKHBvb2wgPT09IG51bGwgfHwgcG9vbCA9PT0gdW5kZWZpbmVkIHx8IHBvb2wubGVuZ3RoID09PSAwKSB7" +
        "XG4iICsKICAiICAgICAgICAgICAgcmV0dXJuIG51bGw7XG4iICsKICAiICAgICAgICB9XG4iICsKICAiICAgICAgICBmb3IgKGluZGV4ID0gcG9vbC5sZW5n" +
        "dGggLSAxOyBpbmRleCA+PSAwOyBpbmRleCAtPSAxKSB7XG4iICsKICAiICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xl" +
        "UG9vbFNjYW5Db3VudCArPSAxO1xuIiArCiAgIiAgICAgICAgICAgIGlmIChyZXN1bHRDYXJkUmVjeWNsZUtleUZvckhvbGRlcihwb29sW2luZGV4XSkgPT09" +
        "IGtleSkge1xuIiArCiAgIiAgICAgICAgICAgICAgICByZXR1cm4gcG9vbC5zcGxpY2UoaW5kZXgsIDEpWzBdO1xuIiArCiAgIiAgICAgICAgICAgIH1cbiIg" +
        "KwogICIgICAgICAgIH1cbiIgKwogICIgICAgICAgIHJldHVybiBudWxsO1xuIiArCiAgIiAgICB9XG5cbiI7CgogICAgICAgIHNvdXJjZSA9IHJlcGxhY2VP" +
        "bmNlU3RyaWN0KHNvdXJjZSwKICAiICAgIGZ1bmN0aW9uIHJlYnVpbGRWaXJ0dWFsV2luZG93KG9yaWdpbiwgZm9yY2UsIHByZWZlcnJlZEluZGV4KSB7IiwK" +
        "ICBoZWxwZXJUZXh0ICsgIiAgICBmdW5jdGlvbiByZWJ1aWxkVmlydHVhbFdpbmRvdyhvcmlnaW4sIGZvcmNlLCBwcmVmZXJyZWRJbmRleCkgeyIsCiAgIlN0" +
        "YWdlMTZDIHJlY3ljbGUgaGVscGVycyIpOwoKICAgICAgICBzb3VyY2UgPSByZXBsYWNlT25jZVN0cmljdChzb3VyY2UsCiAgIiAgICAgICAgdmFyIHJlYnVp" +
        "bGRSZXVzZWRCZWZvcmU7XG4iLAogICIgICAgICAgIHZhciByZWJ1aWxkUmV1c2VkQmVmb3JlO1xuIiArCiAgIiAgICAgICAgdmFyIHJlYnVpbGRSZWN5Y2xl" +
        "QmVmb3JlID1cbiIgKwogICIgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlUmV1c2VDb3VudCk7XG4iLAog" +
        "ICJTdGFnZTE2QyBzbG93IHNhbXBsZSBiYXNlbGluZSIpOwoKICAgICAgICBvbGRUYWtlID0KICAiICAgICAgICAgICAgICAgICAgICBpZiAocmVjeWNsZUVu" +
        "YWJsZWQgJiYgcmVjeWNsZVBvb2wubGVuZ3RoID4gMCkge1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgIGhvbGRlclJlZiA9IHJlY3ljbGVQb29s" +
        "LnBvcCgpO1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgIGlmIChyZWJpbmRSZXN1bHRDYXJkSG9sZGVyKGhvbGRlclJlZixcbiIgKwogICIgICAg" +
        "ICAgICAgICAgICAgICAgICAgICAgICAgICAgIHByZXZpZXdSb3dzW2luZGV4XSwgY29sb3JzKSkge1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAg" +
        "ICAgICB3cmFwcGVyID0gaG9sZGVyUmVmLndyYXBwZXI7XG4iICsKICAiICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNhcmRSZWYgPSBob2xkZXJSZWYu" +
        "Y2FyZDtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWN0aW9uUmVmID0gY2FyZEhvbGRlckFjdGlvblJlZnMoaG9sZGVyUmVmKTtcbiIg" +
        "KwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlUmV1c2VDb3VudCArPSAxO1xuIiAr" +
        "CiAgIiAgICAgICAgICAgICAgICAgICAgICAgIH0gZWxzZSB7XG4iICsKICAiICAgICAgICAgICAgICAgICAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNl" +
        "U3RhdGUuaG9sZGVyUmVjeWNsZURpc2NhcmRDb3VudCArPSAxO1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgICAgICBob2xkZXJSZWYgPSBudWxs" +
        "O1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgIH1cbiIgKwogICIgICAgICAgICAgICAgICAgICAgIH1cbiI7CgogICAgICAgIG5ld1Rha2UgPQog" +
        "ICIgICAgICAgICAgICAgICAgICAgIGlmIChyZWN5Y2xlRW5hYmxlZCAmJiByZWN5Y2xlUG9vbC5sZW5ndGggPiAwKSB7XG4iICsKICAiICAgICAgICAgICAg" +
        "ICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlUG9vbFBlYWtDb3VudCA9IE1hdGgubWF4KFxuIiArCiAgIiAgICAgICAg" +
        "ICAgICAgICAgICAgICAgICAgICBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlUG9vbFBlYWtDb3VudCksXG4iICsKICAiICAg" +
        "ICAgICAgICAgICAgICAgICAgICAgICAgIE51bWJlcihyZWN5Y2xlUG9vbC5sZW5ndGgpKTtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICBob2xk" +
        "ZXJSZWYgPSB0YWtlQ29tcGF0aWJsZVJlY3ljbGVIb2xkZXIoXG4iICsKICAiICAgICAgICAgICAgICAgICAgICAgICAgICAgIHJlY3ljbGVQb29sLCBwcmV2" +
        "aWV3Um93c1tpbmRleF0pO1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgIGlmIChob2xkZXJSZWYgIT09IG51bGwgJiYgaG9sZGVyUmVmICE9PSB1" +
        "bmRlZmluZWQpIHtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlS2V5SGl0" +
        "Q291bnQgKz0gMTtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgKHJlYmluZFJlc3VsdENhcmRIb2xkZXIoaG9sZGVyUmVmLFxuIiAr" +
        "CiAgIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHByZXZpZXdSb3dzW2luZGV4XSwgY29sb3JzKSkge1xuIiArCiAgIiAgICAgICAgICAg" +
        "ICAgICAgICAgICAgICAgICAgICAgd3JhcHBlciA9IGhvbGRlclJlZi53cmFwcGVyO1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg" +
        "Y2FyZFJlZiA9IGhvbGRlclJlZi5jYXJkO1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWN0aW9uUmVmID0gY2FyZEhvbGRlckFj" +
        "dGlvblJlZnMoaG9sZGVyUmVmKTtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVy" +
        "UmVjeWNsZVJldXNlQ291bnQgKz0gMTtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgfSBlbHNlIHtcbiIgKwogICIgICAgICAgICAgICAg" +
        "ICAgICAgICAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZURpc2NhcmRDb3VudCArPSAxO1xuIiArCiAgIiAgICAgICAg" +
        "ICAgICAgICAgICAgICAgICAgICAgICAgaG9sZGVyUmVmID0gbnVsbDtcbiIgKwogICIgICAgICAgICAgICAgICAgICAgICAgICAgICAgfVxuIiArCiAgIiAg" +
        "ICAgICAgICAgICAgICAgICAgICAgIH0gZWxzZSB7XG4iICsKICAiICAgICAgICAgICAgICAgICAgICAgICAgICAgIHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUu" +
        "aG9sZGVyUmVjeWNsZUtleU1pc3NDb3VudCArPSAxO1xuIiArCiAgIiAgICAgICAgICAgICAgICAgICAgICAgIH1cbiIgKwogICIgICAgICAgICAgICAgICAg" +
        "ICAgIH1cbiI7CgogICAgICAgIHNvdXJjZSA9IHJlcGxhY2VBbGxTdGFnZTE2Qyhzb3VyY2UsIG9sZFRha2UsIG5ld1Rha2UsIDIsCiAgIlN0YWdlMTZDIGNv" +
        "bXBhdGlibGUgaG9sZGVyIHRha2UiKTsKCiAgICAgICAgc291cmNlID0gcmVwbGFjZU9uY2VTdHJpY3Qoc291cmNlLAogICIgICAgICAgICAgICAgICAgcmV1" +
        "c2VkOiBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5zYW1lSWRSZXVzZUNvdW50KSAtXG4iICsKICAiICAgICAgICAgICAgICAgICAgICByZWJ1aWxk" +
        "UmV1c2VkQmVmb3JlLFxuIiArCiAgIiAgICAgICAgICAgICAgICBtZWFzdXJlTXM6IE51bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLm1lYXN1cmVMYXN0" +
        "TXMpLFxuIiwKICAiICAgICAgICAgICAgICAgIHJldXNlZDogTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuc2FtZUlkUmV1c2VDb3VudCkgLVxuIiAr" +
        "CiAgIiAgICAgICAgICAgICAgICAgICAgcmVidWlsZFJldXNlZEJlZm9yZSxcbiIgKwogICIgICAgICAgICAgICAgICAgcmVjeWNsZWQ6IE51bWJlcihzY3Jv" +
        "bGxQZXJmb3JtYW5jZVN0YXRlLmhvbGRlclJlY3ljbGVSZXVzZUNvdW50KSAtXG4iICsKICAiICAgICAgICAgICAgICAgICAgICByZWJ1aWxkUmVjeWNsZUJl" +
        "Zm9yZSxcbiIgKwogICIgICAgICAgICAgICAgICAgbmV3QnVpbHQ6IE1hdGgubWF4KDAsXG4iICsKICAiICAgICAgICAgICAgICAgICAgICBOdW1iZXIoc2Ny" +
        "b2xsUGVyZm9ybWFuY2VTdGF0ZS5jcmVhdGVkVmlld0NvdW50KSAtXG4iICsKICAiICAgICAgICAgICAgICAgICAgICByZWJ1aWxkQ3JlYXRlZEJlZm9yZSAt" +
        "XG4iICsKICAiICAgICAgICAgICAgICAgICAgICAoTnVtYmVyKHNjcm9sbFBlcmZvcm1hbmNlU3RhdGUuaG9sZGVyUmVjeWNsZVJldXNlQ291bnQpIC1cbiIg" +
        "KwogICIgICAgICAgICAgICAgICAgICAgICAgICByZWJ1aWxkUmVjeWNsZUJlZm9yZSkpLFxuIiArCiAgIiAgICAgICAgICAgICAgICBtZWFzdXJlTXM6IE51" +
        "bWJlcihzY3JvbGxQZXJmb3JtYW5jZVN0YXRlLm1lYXN1cmVMYXN0TXMpLFxuIiwKICAiU3RhZ2UxNkMgc2xvdyBzYW1wbGUgYnJlYWtkb3duIik7CgogICAg" +
        "ICAgIGlmIChzb3VyY2UuaW5kZXhPZigiTU9EVUxFX1ZFUlNJT046IDY0IikgPCAwIHx8CiAgICAgIHNvdXJjZS5pbmRleE9mKCJ0YWtlQ29tcGF0aWJsZVJl" +
        "Y3ljbGVIb2xkZXIiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4T2YoImhvbGRlclJlY3ljbGVLZXlIaXRDb3VudCIpIDwgMCB8fAogICAgICBzb3VyY2Uu" +
        "aW5kZXhPZigiaG9sZGVyUmVjeWNsZUtleU1pc3NDb3VudCIpIDwgMCB8fAogICAgICBzb3VyY2UuaW5kZXhPZigiaG9sZGVyUmVjeWNsZVBvb2xTY2FuQ291" +
        "bnQiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4T2YoInJlY3ljbGVkOiBOdW1iZXIoc2Nyb2xsUGVyZm9ybWFuY2VTdGF0ZS5ob2xkZXJSZWN5Y2xlUmV1" +
        "c2VDb3VudCkiKSA8IDAgfHwKICAgICAgc291cmNlLmluZGV4T2YoIm5ld0J1aWx0OiBNYXRoLm1heCgwIikgPCAwIHx8CiAgICAgIHNvdXJjZS5pbmRleE9m" +
        "KG9sZFRha2UpID49IDApIHsKICB0aHJvdyBuZXcgRXJyb3IoIlN0YWdlMTZDIHdpcmluZyBpbmNvbXBsZXRlIik7CiAgICAgICAgfQogICAgICAgIHJldHVy" +
        "biBzb3VyY2U7CiAgICB9Cg==";





    function closeQuietly(value) {
        if (value !== null && value !== undefined) {
            try { value.close(); } catch (ignored) {}
        }
    }

    function readBytes(stream) {
        var output = new BAOS();
        var buffer = ReflectArray.newInstance(JavaByte.TYPE, 8192);
        var count;
        try {
            while ((count = stream.read(buffer)) >= 0) {
                if (count > 0) { output.write(buffer, 0, count); }
            }
            return output.toByteArray();
        } finally {
            closeQuietly(stream);
            closeQuietly(output);
        }
    }

    function readUtf8(file) {
        return String(new JavaString(readBytes(new FIS(file)), "UTF-8"));
    }

    function ensureDir(dir) {
        if (!dir.exists() && !dir.mkdirs() && !dir.isDirectory()) {
            throw new Error("Cannot create directory: " +
                String(dir.getAbsolutePath()));
        }
        return dir;
    }

    function writeUtf8Atomic(file, text) {
        var parent = ensureDir(file.getParentFile());
        var temp = new File(parent, file.getName() + ".tmp");
        var output = null;
        try {
            output = new FOS(temp, false);
            output.write(new JavaString(String(text)).getBytes("UTF-8"));
            output.flush();
        } finally {
            closeQuietly(output);
        }
        if (file.exists() && !file.delete()) {
            temp.delete();
            throw new Error("Cannot replace cache: " +
                String(file.getAbsolutePath()));
        }
        if (!temp.renameTo(file)) {
            temp.delete();
            throw new Error("Cannot commit cache: " +
                String(file.getAbsolutePath()));
        }
    }

    function gitBlobSha1(text) {
        var bytes = new JavaString(String(text)).getBytes("UTF-8");
        var header = new JavaString("blob " + bytes.length + "\u0000")
            .getBytes("UTF-8");
        var digest = MessageDigest.getInstance("SHA-1");
        var result;
        var parts = [];
        var index;
        var value;
        digest.update(header);
        digest.update(bytes);
        result = digest.digest();
        for (index = 0; index < result.length; index += 1) {
            value = Number(result[index]);
            if (value < 0) { value += 256; }
            parts.push((value < 16 ? "0" : "") + value.toString(16));
        }
        return parts.join("");
    }

    function runtimeName() {
        var options = global.ClipHubBootstrapOptions || {};
        var name = options.runtimeName === undefined ?
            "ClipHub" : String(options.runtimeName);
        if (!/^[A-Za-z0-9._-]+$/.test(name) ||
                name === "." || name === "..") {
            throw new Error("Invalid runtime name: " + name);
        }
        return name;
    }

    function fetchBaseline() {
        var connection = null;
        var code;
        var text;
        try {
            connection = new URL(BASE_URL + "?stage16cv18=" +
                Number(Packages.java.lang.System.currentTimeMillis()))
                .openConnection();
            connection.setConnectTimeout(10000);
            connection.setReadTimeout(30000);
            connection.setUseCaches(false);
            connection.setRequestProperty("Accept-Encoding", "identity");
            code = Number(connection.getResponseCode());
            text = String(new JavaString(readBytes(
                code >= 200 && code < 300 ?
                    connection.getInputStream() :
                    connection.getErrorStream()), "UTF-8"));
            if (code < 200 || code >= 300) {
                throw new Error("HTTP " + code + " baseline loader");
            }
            return text;
        } finally {
            if (connection !== null) {
                try { connection.disconnect(); } catch (ignoredDisconnect) {}
            }
        }
    }

    function loadBaseline() {
        var root;
        var cacheFile;
        var text = "";
        if (typeof shortx === "undefined" ||
                typeof shortx.getShortXDir !== "function") {
            throw new Error("ShortX runtime unavailable");
        }
        root = new File(String(shortx.getShortXDir()));
        cacheFile = new File(ensureDir(new File(
            new File(root, runtimeName()), "cache")), CACHE_NAME);
        if (cacheFile.isFile()) {
            try {
                text = readUtf8(cacheFile);
                if (gitBlobSha1(text) === BASE_BLOB_SHA1) {
                    return text;
                }
            } catch (ignoredCache) {}
        }
        text = fetchBaseline();
        if (gitBlobSha1(text) !== BASE_BLOB_SHA1) {
            throw new Error("Stage 16B baseline loader SHA mismatch");
        }
        writeUtf8Atomic(cacheFile, text);
        return text;
    }

    function patchSourceText() {
        return String(new JavaString(
            Base64.decode(String(PATCH_B64), Base64.DEFAULT), "UTF-8"));
    }

    function replaceOnce(text, oldText, newText, label) {
        var first = text.indexOf(oldText);
        if (first < 0) {
            throw new Error("Stage 16B.1 anchor missing: " + label);
        }
        if (text.indexOf(oldText, first + oldText.length) >= 0) {
            throw new Error("Stage 16B.1 anchor duplicate: " + label);
        }
        return text.substring(0, first) + newText +
            text.substring(first + oldText.length);
    }

    function transformBaselineLoader(loader) {
        var oldEval =
            "    try {\n" +
            "        eval(transformRecycleSource(\n" +
            "            transformCardHolderSource(\n" +
            "                transformSource(decodeSource(loadPackedSource())))));\n";
        var newEval =
  patchSourceText() + "\n" +
  "    try {\n" +
  "        eval(transformStage16CSource(\n" +
  "            transformStage16B4Source(\n" +
  "                transformStage16B3Source(\n" +
  "                    transformStage16B2Source(\n" +
  "                        transformRecycleFixSource(\n" +
  "                            transformRecycleSource(\n" +
  "                                transformCardHolderSource(\n" +
  "                                    transformSource(decodeSource(loadPackedSource()))))))))));\n";
        loader = replaceOnce(loader, oldEval, newEval, "baseline eval");
        loader = loader.replace(
            "ch_11_filter.js Stage 16B loader failed:",
            "ch_11_filter.js Stage 16C loader failed:");
        return loader;
    }

    try {
        eval(transformBaselineLoader(loadBaseline()));
    } catch (error) {
        throw new Error("ch_11_filter.js Stage 16C wrapper failed: " +
            String(error));
    }
}((function () { return this; }())));
